;; Integration test for async streams, futures, import calls, poll and await.
;;
;; A program (list<command>) is fed to $Driver's `run` export. run returns nothing; an
;; expect-code mismatch traps, so a passing program is just an assert_return.
;;
;; The $Mock component mocks imports called by the $Testee. The $Driver
;; component imports the $Mock and $Testee to drive the $Testee and control
;; what the $Mock does.
(component definition $Tester

  (component $Types
    (type $event-kind (enum "none" "subtask" "stream-read" "stream-write" "future-read" "future-write"))
    (export $event-kind-e "event-kind" (type $event-kind))
    (type $io-args (record (field "handle" u8) (field "bytes" u32)))
    (export $io-args-e "io-args" (type $io-args))
    (type $poll-expect (record (field "slot" u8) (field "event" $event-kind-e) (field "payload" u32)))
    (export $poll-expect-e "poll-expect" (type $poll-expect))
    (type $command (variant
      (case "stream-new" u8)
      (case "future-new" u8)
      (case "testee-read" $io-args-e)
      (case "testee-write" $io-args-e)
      (case "mock-read" $io-args-e)
      (case "mock-write" $io-args-e)
      (case "call-import" u8)
      (case "poll" $poll-expect-e)
      (case "await" $poll-expect-e)
      (case "drop-readable" u8)
      (case "drop-writable" u8)
      (case "expect-code" s32)
      (case "noop")
      (case "future-read" u8)
      (case "future-write" u8)
      (case "future-drop-readable" u8)
      (case "future-drop-writable" u8)
      (case "call-import-future" u8)))
    (export $command-e "command" (type $command))
  )
  (instance $types (instantiate $Types))
  (export "types" (instance $types))

  (component $Mock
    (core module $Memory (memory (export "mem") 1))
    (core instance $memory (instantiate $Memory))
    (core module $MM
      (import "" "mem" (memory 1))
      (import "" "task.return" (func $task.return))
      (import "" "waitable.join" (func $waitable.join (param i32 i32)))
      (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
      (import "" "stream.read" (func $stream.read (param i32 i32 i32) (result i32)))
      (import "" "stream.drop-readable" (func $stream.drop-readable (param i32)))
      (import "" "future.read" (func $future.read (param i32 i32) (result i32)))
      (import "" "future.drop-readable" (func $future.drop-readable (param i32)))

      (global $ws (mut i32) (i32.const 0))
      (func $start (global.set $ws (call $waitable-set.new)))
      (start $start)
      (global $insr (mut i32) (i32.const 0))
      (global $DST_BUF i32 (i32.const 256))

      (func (export "sink") (param $insr i32) (result i32)
        (local $ret i32)
        (global.set $insr (local.get $insr))
        (local.set $ret (call $stream.read (local.get $insr) (global.get $DST_BUF) (i32.const 4)))
        (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
          (then unreachable))
        (call $task.return)
        (call $waitable.join (local.get $insr) (global.get $ws))
        (i32.or (i32.const 2 (; WAIT ;)) (i32.shl (global.get $ws) (i32.const 4))))
      (func (export "sink_cb") (param $event-code i32) (param $index i32) (param $payload i32) (result i32)
        (if (i32.ne (local.get $event-code) (i32.const 2 (; STREAM_READ ;)))
          (then unreachable))
        (call $stream.drop-readable (local.get $index))
        (i32.const 0 (; EXIT ;)))

      (func (export "sink-future") (param $infr i32) (result i32)
        (local $ret i32)
        (global.set $insr (local.get $infr))
        (local.set $ret (call $future.read (local.get $infr) (global.get $DST_BUF)))
        (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
          (then unreachable))
        (call $task.return)
        (call $waitable.join (local.get $infr) (global.get $ws))
        (i32.or (i32.const 2 (; WAIT ;)) (i32.shl (global.get $ws) (i32.const 4))))
      (func (export "sink-future_cb") (param $event-code i32) (param $index i32) (param $payload i32) (result i32)
        (if (i32.ne (local.get $event-code) (i32.const 4 (; FUTURE_READ ;)))
          (then unreachable))
        (call $future.drop-readable (local.get $index))
        (i32.const 0 (; EXIT ;)))
    )
    (type $ST (stream u8))
    (type $FT (future u8))
    (canon task.return (core func $task.return))
    (canon waitable.join (core func $waitable.join))
    (canon waitable-set.new (core func $waitable-set.new))
    (canon stream.read $ST async (memory $memory "mem") (core func $stream.read))
    (canon stream.drop-readable $ST (core func $stream.drop-readable))
    (canon future.read $FT async (memory $memory "mem") (core func $future.read))
    (canon future.drop-readable $FT (core func $future.drop-readable))
    (core instance $mm (instantiate $MM (with "" (instance
      (export "mem" (memory $memory "mem"))
      (export "task.return" (func $task.return))
      (export "waitable.join" (func $waitable.join))
      (export "waitable-set.new" (func $waitable-set.new))
      (export "stream.read" (func $stream.read))
      (export "stream.drop-readable" (func $stream.drop-readable))
      (export "future.read" (func $future.read))
      (export "future.drop-readable" (func $future.drop-readable))))))
    (func (export "sink") async (param "in" (stream u8)) (canon lift
      (core func $mm "sink") async (memory $memory "mem") (callback (func $mm "sink_cb"))))
    (func (export "sink-future") async (param "in" (future u8)) (canon lift
      (core func $mm "sink-future") async (memory $memory "mem") (callback (func $mm "sink-future_cb"))))
  )

  (component $Testee
    (import "sink" (func $sink async (param "in" (stream u8))))
    (import "sink-future" (func $sink-future async (param "in" (future u8))))
    (core module $Memory (memory (export "mem") 1))
    (core instance $memory (instantiate $Memory))
    (core module $TM
      (import "" "mem" (memory 1))
      (import "" "sink" (func $sink (param i32) (result i32)))
      (import "" "sink-future" (func $sink-future (param i32) (result i32)))
      (import "" "stream.new" (func $stream.new (result i64)))
      (import "" "stream.read" (func $stream.read (param i32 i32 i32) (result i32)))
      (import "" "stream.write" (func $stream.write (param i32 i32 i32) (result i32)))
      (import "" "stream.drop-readable" (func $stream.drop-readable (param i32)))
      (import "" "stream.drop-writable" (func $stream.drop-writable (param i32)))
      (import "" "future.new" (func $future.new (result i64)))
      (import "" "future.read" (func $future.read (param i32 i32) (result i32)))
      (import "" "future.write" (func $future.write (param i32 i32) (result i32)))
      (import "" "future.drop-readable" (func $future.drop-readable (param i32)))
      (import "" "future.drop-writable" (func $future.drop-writable (param i32)))
      (import "" "task.return" (func $task.return))
      (import "" "waitable.join" (func $waitable.join (param i32 i32)))
      (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
      (import "" "waitable-set.poll" (func $waitable-set.poll (param i32 i32) (result i32)))
      (import "" "waitable-set.drop" (func $waitable-set.drop (param i32)))

      (global $RX_BASE i32 (i32.const 0))
      (global $TX_BASE i32 (i32.const 64))
      (global $SRC_BUF i32 (i32.const 128))
      (global $DST_BUF i32 (i32.const 256))
      (global $EVENTP  i32 (i32.const 384))

      (global $AW_WS      (mut i32) (i32.const 0))
      (global $AW_SLOT    (mut i32) (i32.const 0))
      (global $AW_EVENT   (mut i32) (i32.const 0))
      (global $AW_PAYLOAD (mut i32) (i32.const 0))

      (func $rx (param $slot i32) (result i32)
        (i32.load (i32.add (global.get $RX_BASE) (i32.mul (local.get $slot) (i32.const 4)))))
      (func $tx (param $slot i32) (result i32)
        (i32.load (i32.add (global.get $TX_BASE) (i32.mul (local.get $slot) (i32.const 4)))))

      (func (export "call-import") (param $slot i32) (result i32)
        (call $sink (call $rx (local.get $slot))))

      (func (export "call-import-future") (param $slot i32) (result i32)
        (call $sink-future (call $rx (local.get $slot))))

      (func (export "stream-new") (param $slot i32)
        (local $ret64 i64)
        (local.set $ret64 (call $stream.new))
        (i32.store (i32.add (global.get $RX_BASE) (i32.mul (local.get $slot) (i32.const 4)))
          (i32.wrap_i64 (local.get $ret64)))
        (i32.store (i32.add (global.get $TX_BASE) (i32.mul (local.get $slot) (i32.const 4)))
          (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32)))))

      (func (export "testee-write") (param $slot i32) (param $bytes i32) (result i32)
        (call $stream.write (call $tx (local.get $slot)) (global.get $SRC_BUF) (local.get $bytes)))

      (func (export "testee-read") (param $slot i32) (param $bytes i32) (result i32)
        (call $stream.read (call $rx (local.get $slot)) (global.get $DST_BUF) (local.get $bytes)))

      (func (export "future-new") (param $slot i32)
        (local $ret64 i64)
        (local.set $ret64 (call $future.new))
        (i32.store (i32.add (global.get $RX_BASE) (i32.mul (local.get $slot) (i32.const 4)))
          (i32.wrap_i64 (local.get $ret64)))
        (i32.store (i32.add (global.get $TX_BASE) (i32.mul (local.get $slot) (i32.const 4)))
          (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32)))))

      (func (export "future-write") (param $slot i32) (result i32)
        (call $future.write (call $tx (local.get $slot)) (global.get $SRC_BUF)))
      (func (export "future-read") (param $slot i32) (result i32)
        (call $future.read (call $rx (local.get $slot)) (global.get $DST_BUF)))

      (func (export "future-drop-readable") (param $slot i32)
        (call $future.drop-readable (call $rx (local.get $slot))))
      (func (export "future-drop-writable") (param $slot i32)
        (call $future.drop-writable (call $tx (local.get $slot))))

      (func (export "drop-readable") (param $slot i32)
        (call $stream.drop-readable (call $rx (local.get $slot))))
      (func (export "drop-writable") (param $slot i32)
        (call $stream.drop-writable (call $tx (local.get $slot))))

      (func (export "poll") (param $slot i32) (param $expected-event i32) (param $expected-payload i32)
        (local $ws i32) (local $event i32)
        (local.set $ws (call $waitable-set.new))
        (call $waitable.join (call $tx (local.get $slot)) (local.get $ws))
        (local.set $event (call $waitable-set.poll (local.get $ws) (global.get $EVENTP)))
        (if (i32.ne (local.get $event) (local.get $expected-event))
          (then unreachable))
        (if (i32.ne (i32.load offset=4 (global.get $EVENTP)) (local.get $expected-payload))
          (then unreachable))
        (call $waitable.join (call $tx (local.get $slot)) (i32.const 0))
        (call $waitable-set.drop (local.get $ws)))

      (func (export "await") (param $slot i32) (param $expected-event i32) (param $expected-payload i32) (result i32)
        (global.set $AW_SLOT (local.get $slot))
        (global.set $AW_EVENT (local.get $expected-event))
        (global.set $AW_PAYLOAD (local.get $expected-payload))
        (global.set $AW_WS (call $waitable-set.new))
        (call $waitable.join (call $tx (local.get $slot)) (global.get $AW_WS))
        (call $task.return)
        (i32.or (i32.const 2 (; WAIT ;)) (i32.shl (global.get $AW_WS) (i32.const 4))))
      (func (export "await-cb") (param $event-code i32) (param $index i32) (param $payload i32) (result i32)
        (if (i32.ne (local.get $event-code) (global.get $AW_EVENT))
          (then unreachable))
        (if (i32.ne (local.get $payload) (global.get $AW_PAYLOAD))
          (then unreachable))
        (call $waitable.join (call $tx (global.get $AW_SLOT)) (i32.const 0))
        (call $waitable-set.drop (global.get $AW_WS))
        (i32.const 0 (; EXIT ;)))
    )
    (type $ST (stream u8))
    (type $FT (future u8))
    (canon stream.new $ST (core func $stream.new))
    (canon stream.read $ST async (memory $memory "mem") (core func $stream.read))
    (canon stream.write $ST async (memory $memory "mem") (core func $stream.write))
    (canon stream.drop-readable $ST (core func $stream.drop-readable))
    (canon stream.drop-writable $ST (core func $stream.drop-writable))
    (canon future.new $FT (core func $future.new))
    (canon future.read $FT async (memory $memory "mem") (core func $future.read))
    (canon future.write $FT async (memory $memory "mem") (core func $future.write))
    (canon future.drop-readable $FT (core func $future.drop-readable))
    (canon future.drop-writable $FT (core func $future.drop-writable))
    (canon task.return (core func $task.return))
    (canon waitable.join (core func $waitable.join))
    (canon waitable-set.new (core func $waitable-set.new))
    (canon waitable-set.poll (memory $memory "mem") (core func $waitable-set.poll))
    (canon waitable-set.drop (core func $waitable-set.drop))
    (canon lower (func $sink) async (memory $memory "mem") (core func $sink'))
    (canon lower (func $sink-future) async (memory $memory "mem") (core func $sink-future'))
    (core instance $tm (instantiate $TM (with "" (instance
      (export "mem" (memory $memory "mem"))
      (export "sink" (func $sink'))
      (export "sink-future" (func $sink-future'))
      (export "stream.new" (func $stream.new))
      (export "stream.read" (func $stream.read))
      (export "stream.write" (func $stream.write))
      (export "stream.drop-readable" (func $stream.drop-readable))
      (export "stream.drop-writable" (func $stream.drop-writable))
      (export "future.new" (func $future.new))
      (export "future.read" (func $future.read))
      (export "future.write" (func $future.write))
      (export "future.drop-readable" (func $future.drop-readable))
      (export "future.drop-writable" (func $future.drop-writable))
      (export "task.return" (func $task.return))
      (export "waitable.join" (func $waitable.join))
      (export "waitable-set.new" (func $waitable-set.new))
      (export "waitable-set.poll" (func $waitable-set.poll))
      (export "waitable-set.drop" (func $waitable-set.drop))))))
    (func (export "call-import") (param "slot" u8) (result s32) (canon lift (core func $tm "call-import")))
    (func (export "call-import-future") (param "slot" u8) (result s32) (canon lift (core func $tm "call-import-future")))
    (func (export "stream-new") (param "slot" u8) (canon lift (core func $tm "stream-new")))
    (func (export "testee-write") (param "handle" u8) (param "bytes" u32) (result s32) (canon lift (core func $tm "testee-write")))
    (func (export "testee-read") (param "handle" u8) (param "bytes" u32) (result s32) (canon lift (core func $tm "testee-read")))
    (func (export "future-new") (param "slot" u8) (canon lift (core func $tm "future-new")))
    (func (export "future-write") (param "slot" u8) (result s32) (canon lift (core func $tm "future-write")))
    (func (export "future-read") (param "slot" u8) (result s32) (canon lift (core func $tm "future-read")))
    (func (export "future-drop-readable") (param "slot" u8) (canon lift (core func $tm "future-drop-readable")))
    (func (export "future-drop-writable") (param "slot" u8) (canon lift (core func $tm "future-drop-writable")))
    (func (export "drop-readable") (param "slot" u8) (canon lift (core func $tm "drop-readable")))
    (func (export "drop-writable") (param "slot" u8) (canon lift (core func $tm "drop-writable")))
    (func (export "poll") (param "slot" u8) (param "event" u8) (param "payload" u32) (canon lift (core func $tm "poll")))
    (func (export "await") async (param "slot" u8) (param "event" u8) (param "payload" u32) (canon lift
      (core func $tm "await") async (memory $memory "mem") (callback (func $tm "await-cb"))))
  )

  (component $Driver
    (type $event-kind-local (enum "none" "subtask" "stream-read" "stream-write" "future-read" "future-write"))
    (type $io-args-local (record (field "handle" u8) (field "bytes" u32)))
    (import "types" (instance $t
      (export "event-kind" (type $event-kind-x (eq $event-kind-local)))
      (export "io-args" (type $io-args-x (eq $io-args-local)))
      (type $poll-expect-local (record (field "slot" u8) (field "event" $event-kind-x) (field "payload" u32)))
      (export "poll-expect" (type $poll-expect-x (eq $poll-expect-local)))
      (type $command-local (variant
        (case "stream-new" u8)
        (case "future-new" u8)
        (case "testee-read" $io-args-x)
        (case "testee-write" $io-args-x)
        (case "mock-read" $io-args-x)
        (case "mock-write" $io-args-x)
        (case "call-import" u8)
        (case "poll" $poll-expect-x)
        (case "await" $poll-expect-x)
        (case "drop-readable" u8)
        (case "drop-writable" u8)
        (case "expect-code" s32)
        (case "noop")
        (case "future-read" u8)
        (case "future-write" u8)
        (case "future-drop-readable" u8)
        (case "future-drop-writable" u8)
        (case "call-import-future" u8)))
      (export "command" (type $command-x (eq $command-local)))
    ))
    (import "call-import" (func $call-import (param "slot" u8) (result s32)))
    (import "stream-new" (func $stream-new (param "slot" u8)))
    (import "testee-write" (func $testee-write (param "handle" u8) (param "bytes" u32) (result s32)))
    (import "testee-read" (func $testee-read (param "handle" u8) (param "bytes" u32) (result s32)))
    (import "drop-readable" (func $drop-readable (param "slot" u8)))
    (import "drop-writable" (func $drop-writable (param "slot" u8)))
    (import "poll" (func $poll (param "slot" u8) (param "event" u8) (param "payload" u32)))
    (import "await" (func $await async (param "slot" u8) (param "event" u8) (param "payload" u32)))
    (import "future-new" (func $future-new (param "slot" u8)))
    (import "future-write" (func $future-write (param "slot" u8) (result s32)))
    (import "future-read" (func $future-read (param "slot" u8) (result s32)))
    (import "future-drop-readable" (func $future-drop-readable (param "slot" u8)))
    (import "future-drop-writable" (func $future-drop-writable (param "slot" u8)))
    (import "call-import-future" (func $call-import-future (param "slot" u8) (result s32)))

    (core module $DM
      (import "" "call-import" (func $call-import (param i32) (result i32)))
      (import "" "stream-new" (func $stream-new (param i32)))
      (import "" "testee-write" (func $testee-write (param i32 i32) (result i32)))
      (import "" "testee-read" (func $testee-read (param i32 i32) (result i32)))
      (import "" "future-new" (func $future-new (param i32)))
      (import "" "future-write" (func $future-write (param i32) (result i32)))
      (import "" "future-read" (func $future-read (param i32) (result i32)))
      (import "" "future-drop-readable" (func $future-drop-readable (param i32)))
      (import "" "future-drop-writable" (func $future-drop-writable (param i32)))
      (import "" "call-import-future" (func $call-import-future (param i32) (result i32)))
      (import "" "drop-readable" (func $drop-readable (param i32)))
      (import "" "drop-writable" (func $drop-writable (param i32)))
      (import "" "poll" (func $poll (param i32 i32 i32)))
      (import "" "await" (func $await (param i32 i32 i32) (result i32)))
      (memory (export "mem") 1)

      (global $w (mut i32) (i32.const 1024))
      (func (export "realloc") (param $old i32) (param $os i32) (param $al i32) (param $ns i32) (result i32)
        (local $r i32)
        (global.set $w (i32.and (i32.add (global.get $w) (i32.const 7)) (i32.const -8)))
        (local.set $r (global.get $w))
        (global.set $w (i32.add (global.get $w) (local.get $ns)))
        (local.get $r))

      (global $STREAM_NEW    i32 (i32.const 0))
      (global $FUTURE_NEW    i32 (i32.const 1))
      (global $TESTEE_READ   i32 (i32.const 2))
      (global $TESTEE_WRITE  i32 (i32.const 3))
      (global $MOCK_READ     i32 (i32.const 4))
      (global $MOCK_WRITE    i32 (i32.const 5))
      (global $CALL_IMPORT   i32 (i32.const 6))
      (global $POLL          i32 (i32.const 7))
      (global $AWAIT         i32 (i32.const 8))
      (global $DROP_READABLE i32 (i32.const 9))
      (global $DROP_WRITABLE i32 (i32.const 10))
      (global $EXPECT_CODE   i32 (i32.const 11))
      (global $NOOP          i32 (i32.const 12))
      (global $FUTURE_READ   i32 (i32.const 13))
      (global $FUTURE_WRITE  i32 (i32.const 14))
      (global $FUTURE_DROP_READABLE i32 (i32.const 15))
      (global $FUTURE_DROP_WRITABLE i32 (i32.const 16))
      (global $CALL_IMPORT_FUTURE   i32 (i32.const 17))

      (global $last (mut i32) (i32.const 0))
      (global $VOID_OK i32 (i32.const 1337))

      (func (export "run") (param $ptr i32) (param $len i32)
        (local $i i32) (local $insn i32) (local $op i32) (local $slot i32) (local $bytes i32)
        (global.set $last (i32.const 0))
        (block $done
          (loop $loop
            (br_if $done (i32.ge_u (local.get $i) (local.get $len)))
            (local.set $insn (i32.add (local.get $ptr) (i32.mul (local.get $i) (i32.const 12))))
            (local.set $op (i32.load8_u offset=0 (local.get $insn)))

            (if (i32.eq (local.get $op) (global.get $STREAM_NEW))
              (then
                (call $stream-new (i32.load8_u offset=4 (local.get $insn)))
                (global.set $last (global.get $VOID_OK))))

            (if (i32.eq (local.get $op) (global.get $TESTEE_WRITE))
              (then
                (local.set $slot  (i32.load8_u offset=4 (local.get $insn)))
                (local.set $bytes (i32.load     offset=8 (local.get $insn)))
                (global.set $last (call $testee-write (local.get $slot) (local.get $bytes)))))

            (if (i32.eq (local.get $op) (global.get $TESTEE_READ))
              (then
                (local.set $slot  (i32.load8_u offset=4 (local.get $insn)))
                (local.set $bytes (i32.load     offset=8 (local.get $insn)))
                (global.set $last (call $testee-read (local.get $slot) (local.get $bytes)))))

            (if (i32.eq (local.get $op) (global.get $FUTURE_NEW))
              (then
                (call $future-new (i32.load8_u offset=4 (local.get $insn)))
                (global.set $last (global.get $VOID_OK))))

            (if (i32.eq (local.get $op) (global.get $FUTURE_WRITE))
              (then (global.set $last (call $future-write (i32.load8_u offset=4 (local.get $insn))))))
            (if (i32.eq (local.get $op) (global.get $FUTURE_READ))
              (then (global.set $last (call $future-read (i32.load8_u offset=4 (local.get $insn))))))

            (if (i32.eq (local.get $op) (global.get $FUTURE_DROP_READABLE))
              (then
                (call $future-drop-readable (i32.load8_u offset=4 (local.get $insn)))
                (global.set $last (global.get $VOID_OK))))
            (if (i32.eq (local.get $op) (global.get $FUTURE_DROP_WRITABLE))
              (then
                (call $future-drop-writable (i32.load8_u offset=4 (local.get $insn)))
                (global.set $last (global.get $VOID_OK))))

            (if (i32.eq (local.get $op) (global.get $DROP_READABLE))
              (then
                (call $drop-readable (i32.load8_u offset=4 (local.get $insn)))
                (global.set $last (global.get $VOID_OK))))
            (if (i32.eq (local.get $op) (global.get $DROP_WRITABLE))
              (then
                (call $drop-writable (i32.load8_u offset=4 (local.get $insn)))
                (global.set $last (global.get $VOID_OK))))

            (if (i32.eq (local.get $op) (global.get $CALL_IMPORT))
              (then (global.set $last (call $call-import (i32.load8_u offset=4 (local.get $insn))))))

            (if (i32.eq (local.get $op) (global.get $CALL_IMPORT_FUTURE))
              (then (global.set $last (call $call-import-future (i32.load8_u offset=4 (local.get $insn))))))

            (if (i32.eq (local.get $op) (global.get $POLL))
              (then
                (call $poll
                  (i32.load8_u offset=4 (local.get $insn))
                  (i32.load8_u offset=5 (local.get $insn))
                  (i32.load     offset=8 (local.get $insn)))
                (global.set $last (global.get $VOID_OK))))

            (if (i32.eq (local.get $op) (global.get $AWAIT))
              (then
                (global.set $last (call $await
                  (i32.load8_u offset=4 (local.get $insn))
                  (i32.load8_u offset=5 (local.get $insn))
                  (i32.load     offset=8 (local.get $insn))))))

            (if (i32.eq (local.get $op) (global.get $EXPECT_CODE))
              (then
                (if (i32.ne (global.get $last) (i32.load offset=4 (local.get $insn)))
                  (then unreachable))))

            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $loop)
          )
        )
      )
    )

    (canon lower (func $call-import) (core func $call-import'))
    (canon lower (func $call-import-future) (core func $call-import-future'))
    (canon lower (func $stream-new) (core func $stream-new'))
    (canon lower (func $testee-write) (core func $testee-write'))
    (canon lower (func $testee-read) (core func $testee-read'))
    (canon lower (func $future-new) (core func $future-new'))
    (canon lower (func $future-write) (core func $future-write'))
    (canon lower (func $future-read) (core func $future-read'))
    (canon lower (func $future-drop-readable) (core func $future-drop-readable'))
    (canon lower (func $future-drop-writable) (core func $future-drop-writable'))
    (canon lower (func $drop-readable) (core func $drop-readable'))
    (canon lower (func $drop-writable) (core func $drop-writable'))
    (canon lower (func $poll) (core func $poll'))
    (canon lower (func $await) async (core func $await'))
    (core instance $dm (instantiate $DM (with "" (instance
      (export "call-import" (func $call-import'))
      (export "call-import-future" (func $call-import-future'))
      (export "stream-new" (func $stream-new'))
      (export "testee-write" (func $testee-write'))
      (export "testee-read" (func $testee-read'))
      (export "future-new" (func $future-new'))
      (export "future-write" (func $future-write'))
      (export "future-read" (func $future-read'))
      (export "future-drop-readable" (func $future-drop-readable'))
      (export "future-drop-writable" (func $future-drop-writable'))
      (export "drop-readable" (func $drop-readable'))
      (export "drop-writable" (func $drop-writable'))
      (export "poll" (func $poll'))
      (export "await" (func $await'))))))
    (alias export $t "command" (type $command))
    (func (export "run") (param "prog" (list $command))
      (canon lift (core func $dm "run") (memory $dm "mem") (realloc (func $dm "realloc")))))

  (instance $mock (instantiate $Mock))
  (instance $testee (instantiate $Testee
    (with "sink" (func $mock "sink"))
    (with "sink-future" (func $mock "sink-future"))))
  (instance $driver (instantiate $Driver
    (with "types" (instance $types))
    (with "call-import" (func $testee "call-import"))
    (with "call-import-future" (func $testee "call-import-future"))
    (with "stream-new" (func $testee "stream-new"))
    (with "testee-write" (func $testee "testee-write"))
    (with "testee-read" (func $testee "testee-read"))
    (with "future-new" (func $testee "future-new"))
    (with "future-write" (func $testee "future-write"))
    (with "future-read" (func $testee "future-read"))
    (with "future-drop-readable" (func $testee "future-drop-readable"))
    (with "future-drop-writable" (func $testee "future-drop-writable"))
    (with "drop-readable" (func $testee "drop-readable"))
    (with "drop-writable" (func $testee "drop-writable"))
    (with "poll" (func $testee "poll"))
    (with "await" (func $testee "await"))))
  (alias export $driver "run" (func $run))
  (export "run" (func $run))
)

(component instance $i $Tester)

(assert_return (invoke "run" (list.const)))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 0))
      (variant.const "expect-code" (s32.const 1337))
      (variant.const "drop-writable" (u8.const 0))
      (variant.const "drop-readable" (u8.const 0))
      (variant.const "expect-code" (s32.const 1337)))))

(assert_trap
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 0))
      (variant.const "expect-code" (s32.const 99))))
  "unreachable")
(component instance $i $Tester)

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 0))
      (variant.const "testee-write" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-read" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 0) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "drop-writable" (u8.const 0))
      (variant.const "drop-readable" (u8.const 0)))))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 1))
      (variant.const "drop-writable" (u8.const 1))
      (variant.const "drop-readable" (u8.const 1)))))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 2))
      (variant.const "call-import" (u8.const 2))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "testee-write" (record.const (field "handle" u8.const 2) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "drop-writable" (u8.const 2)))))

;; TODO: drop the two ends mentioned below
;; await, the blocking analog of poll: after the round-trip, await blocks via its callback
;; for the STREAM_WRITE event, asserts it, and resolves RETURNED=2.
;; The ends are left undropped on purpose. await task.returns eagerly, so await-cb may run
;; only after await returns here, while the writable end is still busy — a drop would trap.
(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 3))
      (variant.const "testee-write" (record.const (field "handle" u8.const 3) (field "bytes" u32.const 4)))
      (variant.const "testee-read" (record.const (field "handle" u8.const 3) (field "bytes" u32.const 4)))
      (variant.const "await" (record.const (field "slot" u8.const 3) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "expect-code" (s32.const 2)))))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "future-new" (u8.const 4))
      (variant.const "future-write" (u8.const 4))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "future-read" (u8.const 4))
      (variant.const "expect-code" (s32.const 0))
      (variant.const "poll" (record.const (field "slot" u8.const 4) (field "event" enum.const "future-write") (field "payload" u32.const 0)))
      (variant.const "future-drop-writable" (u8.const 4))
      (variant.const "future-drop-readable" (u8.const 4)))))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "future-new" (u8.const 5))
      (variant.const "call-import-future" (u8.const 5))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "future-write" (u8.const 5))
      (variant.const "expect-code" (s32.const 0))
      (variant.const "future-drop-writable" (u8.const 5)))))

(assert_trap
  (invoke "run"
    (list.const
      (variant.const "future-new" (u8.const 11))
      (variant.const "future-drop-writable" (u8.const 11))))
  "cannot drop future write end without first writing a value")
(component instance $i $Tester)

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 6))
      (variant.const "stream-new" (u8.const 7))
      (variant.const "testee-write" (record.const (field "handle" u8.const 6) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 7) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-read" (record.const (field "handle" u8.const 7) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 6) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 6) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 7) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "drop-writable" (u8.const 6))
      (variant.const "drop-readable" (u8.const 6))
      (variant.const "drop-writable" (u8.const 7))
      (variant.const "drop-readable" (u8.const 7)))))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 8))
      (variant.const "testee-write" (record.const (field "handle" u8.const 8) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "poll" (record.const (field "slot" u8.const 8) (field "event" enum.const "none") (field "payload" u32.const 0)))
      (variant.const "testee-read" (record.const (field "handle" u8.const 8) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "await" (record.const (field "slot" u8.const 8) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "expect-code" (s32.const 2)))))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 9))
      (variant.const "stream-new" (u8.const 10))
      (variant.const "call-import" (u8.const 9))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "testee-write" (record.const (field "handle" u8.const 10) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 9) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 10) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "drop-writable" (u8.const 9))
      (variant.const "poll" (record.const (field "slot" u8.const 10) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "drop-writable" (u8.const 10))
      (variant.const "drop-readable" (u8.const 10)))))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 0))
      (variant.const "stream-new" (u8.const 1))
      (variant.const "stream-new" (u8.const 2))
      (variant.const "stream-new" (u8.const 3))
      (variant.const "stream-new" (u8.const 4))
      (variant.const "stream-new" (u8.const 5))
      (variant.const "stream-new" (u8.const 6))
      (variant.const "stream-new" (u8.const 7))
      (variant.const "testee-write" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 2) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 3) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 4) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 5) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 6) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 7) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-read" (record.const (field "handle" u8.const 3) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 7) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 5) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 6) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 2) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 4) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 0) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 1) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 2) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 3) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 4) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 5) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 6) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 7) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "drop-writable" (u8.const 0)) (variant.const "drop-readable" (u8.const 0))
      (variant.const "drop-writable" (u8.const 1)) (variant.const "drop-readable" (u8.const 1))
      (variant.const "drop-writable" (u8.const 2)) (variant.const "drop-readable" (u8.const 2))
      (variant.const "drop-writable" (u8.const 3)) (variant.const "drop-readable" (u8.const 3))
      (variant.const "drop-writable" (u8.const 4)) (variant.const "drop-readable" (u8.const 4))
      (variant.const "drop-writable" (u8.const 5)) (variant.const "drop-readable" (u8.const 5))
      (variant.const "drop-writable" (u8.const 6)) (variant.const "drop-readable" (u8.const 6))
      (variant.const "drop-writable" (u8.const 7)) (variant.const "drop-readable" (u8.const 7)))))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 0))
      (variant.const "stream-new" (u8.const 1))
      (variant.const "stream-new" (u8.const 2))
      (variant.const "stream-new" (u8.const 3))
      (variant.const "stream-new" (u8.const 4))
      (variant.const "call-import" (u8.const 0))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "call-import" (u8.const 1))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "call-import" (u8.const 2))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "call-import" (u8.const 3))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "call-import" (u8.const 4))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "testee-write" (record.const (field "handle" u8.const 2) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-write" (record.const (field "handle" u8.const 4) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-write" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-write" (record.const (field "handle" u8.const 3) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-write" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "drop-writable" (u8.const 0))
      (variant.const "drop-writable" (u8.const 1))
      (variant.const "drop-writable" (u8.const 2))
      (variant.const "drop-writable" (u8.const 3))
      (variant.const "drop-writable" (u8.const 4)))))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 0))
      (variant.const "future-new" (u8.const 3))
      (variant.const "stream-new" (u8.const 1))
      (variant.const "future-new" (u8.const 4))
      (variant.const "stream-new" (u8.const 2))
      (variant.const "future-new" (u8.const 5))
      (variant.const "testee-write" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "future-write" (u8.const 3))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "future-write" (u8.const 4))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 2) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "future-write" (u8.const 5))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "future-read" (u8.const 4))
      (variant.const "expect-code" (s32.const 0))
      (variant.const "testee-read" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "future-read" (u8.const 3))
      (variant.const "expect-code" (s32.const 0))
      (variant.const "testee-read" (record.const (field "handle" u8.const 2) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "future-read" (u8.const 5))
      (variant.const "expect-code" (s32.const 0))
      (variant.const "testee-read" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 0) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 3) (field "event" enum.const "future-write") (field "payload" u32.const 0)))
      (variant.const "poll" (record.const (field "slot" u8.const 1) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 4) (field "event" enum.const "future-write") (field "payload" u32.const 0)))
      (variant.const "poll" (record.const (field "slot" u8.const 2) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 5) (field "event" enum.const "future-write") (field "payload" u32.const 0)))
      (variant.const "drop-writable" (u8.const 0)) (variant.const "drop-readable" (u8.const 0))
      (variant.const "drop-writable" (u8.const 1)) (variant.const "drop-readable" (u8.const 1))
      (variant.const "drop-writable" (u8.const 2)) (variant.const "drop-readable" (u8.const 2))
      (variant.const "future-drop-writable" (u8.const 3)) (variant.const "future-drop-readable" (u8.const 3))
      (variant.const "future-drop-writable" (u8.const 4)) (variant.const "future-drop-readable" (u8.const 4))
      (variant.const "future-drop-writable" (u8.const 5)) (variant.const "future-drop-readable" (u8.const 5)))))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 0))
      (variant.const "stream-new" (u8.const 1))
      (variant.const "future-new" (u8.const 2))
      (variant.const "future-new" (u8.const 3))
      (variant.const "call-import" (u8.const 0))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "call-import-future" (u8.const 2))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "call-import" (u8.const 1))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "call-import-future" (u8.const 3))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "future-write" (u8.const 2))
      (variant.const "expect-code" (s32.const 0))
      (variant.const "testee-write" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "future-write" (u8.const 3))
      (variant.const "expect-code" (s32.const 0))
      (variant.const "testee-write" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "drop-writable" (u8.const 0))
      (variant.const "drop-writable" (u8.const 1))
      (variant.const "future-drop-writable" (u8.const 2))
      (variant.const "future-drop-writable" (u8.const 3)))))

;; TODO: avoid requiring this fresh instance
;; Fresh instance: the import scenarios above leave deferred $Mock callbacks that the runtime
;; pumps at the next blocking point, where a stale one would fire with an unexpected event.
(component instance $i $Tester)

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 0))
      (variant.const "stream-new" (u8.const 1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-read" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 0) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 1) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "testee-write" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-read" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 1) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 0) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "drop-writable" (u8.const 0)) (variant.const "drop-readable" (u8.const 0))
      (variant.const "drop-writable" (u8.const 1)) (variant.const "drop-readable" (u8.const 1)))))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 0))
      (variant.const "stream-new" (u8.const 1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-read" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 0) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 1) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "drop-writable" (u8.const 0)) (variant.const "drop-readable" (u8.const 0))
      (variant.const "drop-writable" (u8.const 1)) (variant.const "drop-readable" (u8.const 1))
      (variant.const "stream-new" (u8.const 0))
      (variant.const "stream-new" (u8.const 1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-read" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 1) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 0) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "drop-writable" (u8.const 0)) (variant.const "drop-readable" (u8.const 0))
      (variant.const "drop-writable" (u8.const 1)) (variant.const "drop-readable" (u8.const 1))
      (variant.const "stream-new" (u8.const 0))
      (variant.const "stream-new" (u8.const 1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-read" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 0) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 1) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "drop-writable" (u8.const 0)) (variant.const "drop-readable" (u8.const 0))
      (variant.const "drop-writable" (u8.const 1)) (variant.const "drop-readable" (u8.const 1)))))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 0))
      (variant.const "stream-new" (u8.const 1))
      (variant.const "stream-new" (u8.const 2))
      (variant.const "stream-new" (u8.const 3))
      (variant.const "stream-new" (u8.const 4))
      (variant.const "stream-new" (u8.const 5))
      (variant.const "stream-new" (u8.const 6))
      (variant.const "call-import" (u8.const 0))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "call-import" (u8.const 1))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "call-import" (u8.const 2))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "testee-write" (record.const (field "handle" u8.const 3) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 4) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-write" (record.const (field "handle" u8.const 5) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 6) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-read" (record.const (field "handle" u8.const 5) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-write" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 3) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 6) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-write" (record.const (field "handle" u8.const 2) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 4) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 3) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 4) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 5) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 6) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "drop-writable" (u8.const 3)) (variant.const "drop-readable" (u8.const 3))
      (variant.const "drop-writable" (u8.const 4)) (variant.const "drop-readable" (u8.const 4))
      (variant.const "drop-writable" (u8.const 5)) (variant.const "drop-readable" (u8.const 5))
      (variant.const "drop-writable" (u8.const 6)) (variant.const "drop-readable" (u8.const 6))
      (variant.const "drop-writable" (u8.const 0))
      (variant.const "drop-writable" (u8.const 1))
      (variant.const "drop-writable" (u8.const 2)))))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 0))
      (variant.const "stream-new" (u8.const 1))
      (variant.const "stream-new" (u8.const 2))
      (variant.const "stream-new" (u8.const 3))
      (variant.const "testee-write" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 2) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 3) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-read" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 2) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-read" (record.const (field "handle" u8.const 3) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "await" (record.const (field "slot" u8.const 0) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "await" (record.const (field "slot" u8.const 1) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "await" (record.const (field "slot" u8.const 2) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "await" (record.const (field "slot" u8.const 3) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "expect-code" (s32.const 2)))))

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 0))
      (variant.const "stream-new" (u8.const 1))
      (variant.const "future-new" (u8.const 2))
      (variant.const "future-new" (u8.const 3))
      (variant.const "stream-new" (u8.const 4))
      (variant.const "stream-new" (u8.const 5))
      (variant.const "future-new" (u8.const 6))
      (variant.const "future-new" (u8.const 7))
      (variant.const "call-import" (u8.const 0))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "call-import-future" (u8.const 2))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "call-import" (u8.const 1))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "call-import-future" (u8.const 3))
      (variant.const "expect-code" (s32.const 2))
      (variant.const "testee-write" (record.const (field "handle" u8.const 4) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "future-write" (u8.const 6))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 5) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "future-write" (u8.const 7))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "future-write" (u8.const 2))
      (variant.const "expect-code" (s32.const 0))
      (variant.const "testee-read" (record.const (field "handle" u8.const 4) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-write" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "future-read" (u8.const 6))
      (variant.const "expect-code" (s32.const 0))
      (variant.const "future-write" (u8.const 3))
      (variant.const "expect-code" (s32.const 0))
      (variant.const "testee-read" (record.const (field "handle" u8.const 5) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "testee-write" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "future-read" (u8.const 7))
      (variant.const "expect-code" (s32.const 0))
      (variant.const "poll" (record.const (field "slot" u8.const 4) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 5) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 6) (field "event" enum.const "future-write") (field "payload" u32.const 0)))
      (variant.const "poll" (record.const (field "slot" u8.const 7) (field "event" enum.const "future-write") (field "payload" u32.const 0)))
      (variant.const "drop-writable" (u8.const 4)) (variant.const "drop-readable" (u8.const 4))
      (variant.const "drop-writable" (u8.const 5)) (variant.const "drop-readable" (u8.const 5))
      (variant.const "future-drop-writable" (u8.const 6)) (variant.const "future-drop-readable" (u8.const 6))
      (variant.const "future-drop-writable" (u8.const 7)) (variant.const "future-drop-readable" (u8.const 7))
      (variant.const "drop-writable" (u8.const 0))
      (variant.const "drop-writable" (u8.const 1))
      (variant.const "future-drop-writable" (u8.const 2))
      (variant.const "future-drop-writable" (u8.const 3)))))

;; TODO: avoid requiring this fresh instance
;; Fresh instance: the capstone's import subtasks leave deferred $Mock callbacks; reset first.
(component instance $i $Tester)

(assert_return
  (invoke "run"
    (list.const
      (variant.const "stream-new" (u8.const 0))
      (variant.const "stream-new" (u8.const 1))
      (variant.const "stream-new" (u8.const 2))
      (variant.const "stream-new" (u8.const 3))
      (variant.const "stream-new" (u8.const 4))
      (variant.const "testee-write" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 2) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 3) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "testee-write" (record.const (field "handle" u8.const 4) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const -1))
      (variant.const "poll" (record.const (field "slot" u8.const 0) (field "event" enum.const "none") (field "payload" u32.const 0)))
      (variant.const "poll" (record.const (field "slot" u8.const 1) (field "event" enum.const "none") (field "payload" u32.const 0)))
      (variant.const "poll" (record.const (field "slot" u8.const 2) (field "event" enum.const "none") (field "payload" u32.const 0)))
      (variant.const "poll" (record.const (field "slot" u8.const 3) (field "event" enum.const "none") (field "payload" u32.const 0)))
      (variant.const "poll" (record.const (field "slot" u8.const 4) (field "event" enum.const "none") (field "payload" u32.const 0)))
      (variant.const "testee-read" (record.const (field "handle" u8.const 2) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 2) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 0) (field "event" enum.const "none") (field "payload" u32.const 0)))
      (variant.const "testee-read" (record.const (field "handle" u8.const 0) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 0) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 4) (field "event" enum.const "none") (field "payload" u32.const 0)))
      (variant.const "testee-read" (record.const (field "handle" u8.const 4) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 4) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 1) (field "event" enum.const "none") (field "payload" u32.const 0)))
      (variant.const "testee-read" (record.const (field "handle" u8.const 1) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 1) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "poll" (record.const (field "slot" u8.const 3) (field "event" enum.const "none") (field "payload" u32.const 0)))
      (variant.const "testee-read" (record.const (field "handle" u8.const 3) (field "bytes" u32.const 4)))
      (variant.const "expect-code" (s32.const 0x40))
      (variant.const "poll" (record.const (field "slot" u8.const 3) (field "event" enum.const "stream-write") (field "payload" u32.const 0x40)))
      (variant.const "drop-writable" (u8.const 0)) (variant.const "drop-readable" (u8.const 0))
      (variant.const "drop-writable" (u8.const 1)) (variant.const "drop-readable" (u8.const 1))
      (variant.const "drop-writable" (u8.const 2)) (variant.const "drop-readable" (u8.const 2))
      (variant.const "drop-writable" (u8.const 3)) (variant.const "drop-readable" (u8.const 3))
      (variant.const "drop-writable" (u8.const 4)) (variant.const "drop-readable" (u8.const 4)))))
