;; A `callback` function resumed by 'subtask.cancel' to receive TASK_CANCELLED
;; runs like any other callback: it may switch to an explicit thread with
;; 'thread.suspend-then-resume', including one belonging to a different task of
;; the same component instance. If the thread it switches to then blocks,
;; control flows back out through 'subtask.cancel', which reports BLOCKED
;; because the cancelled task has not resolved; its callback is still
;; suspended part-way through.

;; The explicit thread belongs to the cancelled task itself.
(component
  (component $C
    (core module $Memory (memory (export "mem") 1))
    (core instance $memory (instantiate $Memory))
    (core module $Table (table (export "tbl") 1 funcref))
    (core instance $table (instantiate $Table))
    (core module $CM
      (import "" "mem" (memory 1))
      (import "" "tbl" (table $tbl 1 funcref))
      (import "" "task.cancel" (func $task.cancel))
      (import "" "future.read" (func $future.read (param i32 i32) (result i32)))
      (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
      (import "" "thread.index" (func $thread.index (result i32)))
      (import "" "thread.new-indirect" (func $thread.new-indirect (param i32 i32) (result i32)))
      (import "" "thread.resume-later" (func $thread.resume-later (param i32)))
      (import "" "thread.suspend-then-resume" (func $thread.suspend-then-resume (param i32) (result i32)))

      (global $futr (mut i32) (i32.const 0))
      (global $park-thread (mut i32) (i32.const 0xdead))
      (global $worker-ran (mut i32) (i32.const 0))
      (func (export "ran") (result i32) (global.get $worker-ran))

      (func $worker (param i32)
        (global.set $worker-ran (i32.const 1))
        ;; block; control returns out through 'subtask.cancel'
        (if (i32.ne (i32.const 0 (; COMPLETED ;))
                    (call $future.read (global.get $futr) (i32.const 16)))
          (then unreachable))
        ;; hand control back to the parked callback
        (call $thread.resume-later (global.get $park-thread)))
      (elem (table $tbl) (i32.const 0) func $worker)

      (func (export "park") (param $f i32) (result i32)
        (global.set $futr (local.get $f))
        (global.set $park-thread (call $thread.index))
        (i32.or (i32.const 2 (; WAIT ;))
                (i32.shl (call $waitable-set.new) (i32.const 4))))
      (func (export "park-cb") (param $event i32) (param i32 i32) (result i32)
        (if (i32.ne (local.get $event) (i32.const 6 (; TASK_CANCELLED ;)))
          (then unreachable))
        (drop (call $thread.suspend-then-resume
                (call $thread.new-indirect (i32.const 0) (i32.const 0))))
        (call $task.cancel)
        (i32.const 0 (; EXIT ;)))
    )
    (type $FT (future))
    (core type $ThreadFT (func (param i32)))
    (alias core export $table "tbl" (core table $tbl))
    (canon task.cancel (core func $task.cancel))
    (canon future.read $FT (memory (core memory $memory "mem")) (core func $future.read))
    (canon waitable-set.new (core func $waitable-set.new))
    (canon thread.index (core func $thread.index))
    (canon thread.new-indirect $ThreadFT (core table $tbl) (core func $thread.new-indirect))
    (canon thread.resume-later (core func $thread.resume-later))
    (canon thread.suspend-then-resume (core func $thread.suspend-then-resume))
    (core instance $cm (instantiate $CM (with "" (instance
      (export "mem" (memory $memory "mem"))
      (export "tbl" (table $tbl))
      (export "task.cancel" (func $task.cancel))
      (export "future.read" (func $future.read))
      (export "waitable-set.new" (func $waitable-set.new))
      (export "thread.index" (func $thread.index))
      (export "thread.new-indirect" (func $thread.new-indirect))
      (export "thread.resume-later" (func $thread.resume-later))
      (export "thread.suspend-then-resume" (func $thread.suspend-then-resume))))))
    (func (export "park") async (param "fut" $FT)
      (canon lift (core func $cm "park") async (callback (core func $cm "park-cb"))))
    (func (export "ran") (result u32) (canon lift (core func $cm "ran")))
  )
  (instance $c (instantiate $C))
  (core module $Memory (memory (export "mem") 1))
  (core instance $memory (instantiate $Memory))
  (type $FT (future))
  (canon future.new $FT (core func $future.new))
  (canon future.write $FT async (memory (core memory $memory "mem")) (core func $future.write))
  (canon lower (func $c "park") async (core func $park'))
  (canon lower (func $c "ran") (core func $ran'))
  (canon subtask.cancel async (core func $subtask.cancel))
  (canon subtask.drop (core func $subtask.drop))
  (canon waitable.join (core func $waitable.join))
  (canon waitable-set.new (core func $waitable-set.new))
  (canon waitable-set.wait (memory (core memory $memory "mem")) (core func $waitable-set.wait))

  (core module $Main
    (import "" "mem" (memory 1))
    (import "" "future.new" (func $future.new (result i64)))
    (import "" "future.write" (func $future.write (param i32 i32) (result i32)))
    (import "" "park" (func $park (param i32) (result i32)))
    (import "" "ran" (func $ran (result i32)))
    (import "" "subtask.cancel" (func $subtask.cancel (param i32) (result i32)))
    (import "" "subtask.drop" (func $subtask.drop (param i32)))
    (import "" "waitable.join" (func $waitable.join (param i32 i32)))
    (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
    (import "" "waitable-set.wait" (func $waitable-set.wait (param i32 i32) (result i32)))
    (func (export "run") (result i32)
      (local $ret64 i64) (local $futr i32) (local $futw i32)
      (local $packed i32) (local $sub i32) (local $ws i32)
      (local.set $ret64 (call $future.new))
      (local.set $futr (i32.wrap_i64 (local.get $ret64)))
      (local.set $futw (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))

      (local.set $packed (call $park (local.get $futr)))
      (if (i32.ne (i32.and (local.get $packed) (i32.const 0xf)) (i32.const 1 (; STARTED ;)))
        (then unreachable))
      (local.set $sub (i32.shr_u (local.get $packed) (i32.const 4)))

      ;; the callback is resumed, switches to the explicit thread, and that
      ;; thread blocks, so control lands back here
      (if (i32.ne (call $subtask.cancel (local.get $sub)) (i32.const -1 (; BLOCKED ;)))
        (then unreachable))
      (if (i32.eqz (call $ran)) (then unreachable))

      ;; unblock the explicit thread, which hands control back to the callback
      (if (i32.ne (i32.const 0 (; COMPLETED ;))
                  (call $future.write (local.get $futw) (i32.const 16)))
        (then unreachable))
      (local.set $ws (call $waitable-set.new))
      (call $waitable.join (local.get $sub) (local.get $ws))
      (if (i32.ne (call $waitable-set.wait (local.get $ws) (i32.const 0))
                  (i32.const 1 (; SUBTASK ;)))
        (then unreachable))
      (if (i32.ne (i32.load (i32.const 0)) (local.get $sub)) (then unreachable))
      (if (i32.ne (i32.load (i32.const 4)) (i32.const 4 (; CANCELLED_BEFORE_RETURNED ;)))
        (then unreachable))
      (call $waitable.join (local.get $sub) (i32.const 0))
      (call $subtask.drop (local.get $sub))
      (i32.const 42))
  )
  (core instance $main (instantiate $Main (with "" (instance
    (export "mem" (memory $memory "mem"))
    (export "future.new" (func $future.new))
    (export "future.write" (func $future.write))
    (export "park" (func $park'))
    (export "ran" (func $ran'))
    (export "subtask.cancel" (func $subtask.cancel))
    (export "subtask.drop" (func $subtask.drop))
    (export "waitable.join" (func $waitable.join))
    (export "waitable-set.new" (func $waitable-set.new))
    (export "waitable-set.wait" (func $waitable-set.wait))))))
  (func (export "run") async (result u32) (canon lift (core func $main "run")))
)
(assert_return (invoke "run") (u32.const 42))

;; The same, but the explicit thread belongs to a different task of the same
;; component instance: 'holder', which spawned it and then blocked.
(component
  (component $C
    (core module $Memory (memory (export "mem") 1))
    (core instance $memory (instantiate $Memory))
    (core module $Table (table (export "tbl") 1 funcref))
    (core instance $table (instantiate $Table))
    (core module $CM
      (import "" "mem" (memory 1))
      (import "" "tbl" (table $tbl 1 funcref))
      (import "" "task.return" (func $task.return (param i32)))
      (import "" "task.cancel" (func $task.cancel))
      (import "" "future.read" (func $future.read (param i32 i32) (result i32)))
      (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
      (import "" "thread.index" (func $thread.index (result i32)))
      (import "" "thread.new-indirect" (func $thread.new-indirect (param i32 i32) (result i32)))
      (import "" "thread.resume-later" (func $thread.resume-later (param i32)))
      (import "" "thread.suspend-then-resume" (func $thread.suspend-then-resume (param i32) (result i32)))

      (global $worker-futr (mut i32) (i32.const 0))
      (global $worker-thread (mut i32) (i32.const 0xdead))
      (global $park-thread (mut i32) (i32.const 0xdead))
      (global $worker-ran (mut i32) (i32.const 0))
      (func (export "ran") (result i32) (global.get $worker-ran))

      ;; an explicit thread of 'holder', left suspended until 'park's callback
      ;; switches to it
      (func $worker (param i32)
        (global.set $worker-ran (i32.const 1))
        (if (i32.ne (i32.const 0 (; COMPLETED ;))
                    (call $future.read (global.get $worker-futr) (i32.const 16)))
          (then unreachable))
        (call $thread.resume-later (global.get $park-thread)))
      (elem (table $tbl) (i32.const 0) func $worker)

      (func (export "holder") (param $f i32)
        (global.set $worker-thread (call $thread.new-indirect (i32.const 0) (i32.const 0)))
        (if (i32.ne (i32.const 0 (; COMPLETED ;))
                    (call $future.read (local.get $f) (i32.const 16)))
          (then unreachable))
        (call $task.return (i32.const 43)))

      (func (export "park") (param $f i32) (result i32)
        (global.set $worker-futr (local.get $f))
        (global.set $park-thread (call $thread.index))
        (i32.or (i32.const 2 (; WAIT ;))
                (i32.shl (call $waitable-set.new) (i32.const 4))))
      (func (export "park-cb") (param $event i32) (param i32 i32) (result i32)
        (if (i32.ne (local.get $event) (i32.const 6 (; TASK_CANCELLED ;)))
          (then unreachable))
        (drop (call $thread.suspend-then-resume (global.get $worker-thread)))
        (call $task.cancel)
        (i32.const 0 (; EXIT ;)))
    )
    (type $FT (future))
    (core type $ThreadFT (func (param i32)))
    (alias core export $table "tbl" (core table $tbl))
    (canon task.return (result u32) (core func $task.return))
    (canon task.cancel (core func $task.cancel))
    (canon future.read $FT (memory (core memory $memory "mem")) (core func $future.read))
    (canon waitable-set.new (core func $waitable-set.new))
    (canon thread.index (core func $thread.index))
    (canon thread.new-indirect $ThreadFT (core table $tbl) (core func $thread.new-indirect))
    (canon thread.resume-later (core func $thread.resume-later))
    (canon thread.suspend-then-resume (core func $thread.suspend-then-resume))
    (core instance $cm (instantiate $CM (with "" (instance
      (export "mem" (memory $memory "mem"))
      (export "tbl" (table $tbl))
      (export "task.return" (func $task.return))
      (export "task.cancel" (func $task.cancel))
      (export "future.read" (func $future.read))
      (export "waitable-set.new" (func $waitable-set.new))
      (export "thread.index" (func $thread.index))
      (export "thread.new-indirect" (func $thread.new-indirect))
      (export "thread.resume-later" (func $thread.resume-later))
      (export "thread.suspend-then-resume" (func $thread.suspend-then-resume))))))
    (func (export "holder") async (param "fut" $FT) (result u32)
      (canon lift (core func $cm "holder") async))
    (func (export "park") async (param "fut" $FT)
      (canon lift (core func $cm "park") async (callback (core func $cm "park-cb"))))
    (func (export "ran") (result u32) (canon lift (core func $cm "ran")))
  )
  (instance $c (instantiate $C))
  (core module $Memory (memory (export "mem") 1))
  (core instance $memory (instantiate $Memory))
  (type $FT (future))
  (canon future.new $FT (core func $future.new))
  (canon future.write $FT async (memory (core memory $memory "mem")) (core func $future.write))
  (canon lower (func $c "holder") async (memory (core memory $memory "mem")) (core func $holder'))
  (canon lower (func $c "park") async (core func $park'))
  (canon lower (func $c "ran") (core func $ran'))
  (canon subtask.cancel async (core func $subtask.cancel))
  (canon subtask.drop (core func $subtask.drop))
  (canon waitable.join (core func $waitable.join))
  (canon waitable-set.new (core func $waitable-set.new))
  (canon waitable-set.wait (memory (core memory $memory "mem")) (core func $waitable-set.wait))

  (core module $Main
    (import "" "mem" (memory 1))
    (import "" "future.new" (func $future.new (result i64)))
    (import "" "future.write" (func $future.write (param i32 i32) (result i32)))
    (import "" "holder" (func $holder (param i32 i32) (result i32)))
    (import "" "park" (func $park (param i32) (result i32)))
    (import "" "ran" (func $ran (result i32)))
    (import "" "subtask.cancel" (func $subtask.cancel (param i32) (result i32)))
    (import "" "subtask.drop" (func $subtask.drop (param i32)))
    (import "" "waitable.join" (func $waitable.join (param i32 i32)))
    (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
    (import "" "waitable-set.wait" (func $waitable-set.wait (param i32 i32) (result i32)))
    (func (export "run") (result i32)
      (local $ret64 i64)
      (local $hr i32) (local $hw i32) (local $wr i32) (local $ww i32)
      (local $packed i32) (local $hsub i32) (local $psub i32) (local $ws i32)
      (local.set $ret64 (call $future.new))
      (local.set $hr (i32.wrap_i64 (local.get $ret64)))
      (local.set $hw (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
      (local.set $ret64 (call $future.new))
      (local.set $wr (i32.wrap_i64 (local.get $ret64)))
      (local.set $ww (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))

      ;; holder spawns the explicit thread and then blocks
      (local.set $packed (call $holder (local.get $hr) (i32.const 24)))
      (if (i32.ne (i32.and (local.get $packed) (i32.const 0xf)) (i32.const 1 (; STARTED ;)))
        (then unreachable))
      (local.set $hsub (i32.shr_u (local.get $packed) (i32.const 4)))
      (local.set $packed (call $park (local.get $wr)))
      (if (i32.ne (i32.and (local.get $packed) (i32.const 0xf)) (i32.const 1 (; STARTED ;)))
        (then unreachable))
      (local.set $psub (i32.shr_u (local.get $packed) (i32.const 4)))

      ;; park's callback switches to holder's explicit thread, which blocks
      (if (i32.ne (call $subtask.cancel (local.get $psub)) (i32.const -1 (; BLOCKED ;)))
        (then unreachable))
      (if (i32.eqz (call $ran)) (then unreachable))

      (local.set $ws (call $waitable-set.new))
      (if (i32.ne (i32.const 0 (; COMPLETED ;))
                  (call $future.write (local.get $ww) (i32.const 16)))
        (then unreachable))
      (call $waitable.join (local.get $psub) (local.get $ws))
      (if (i32.ne (call $waitable-set.wait (local.get $ws) (i32.const 0))
                  (i32.const 1 (; SUBTASK ;)))
        (then unreachable))
      (if (i32.ne (i32.load (i32.const 0)) (local.get $psub)) (then unreachable))
      (if (i32.ne (i32.load (i32.const 4)) (i32.const 4 (; CANCELLED_BEFORE_RETURNED ;)))
        (then unreachable))
      (call $waitable.join (local.get $psub) (i32.const 0))
      (call $subtask.drop (local.get $psub))

      (if (i32.ne (i32.const 0 (; COMPLETED ;))
                  (call $future.write (local.get $hw) (i32.const 16)))
        (then unreachable))
      (call $waitable.join (local.get $hsub) (local.get $ws))
      (if (i32.ne (call $waitable-set.wait (local.get $ws) (i32.const 0))
                  (i32.const 1 (; SUBTASK ;)))
        (then unreachable))
      (if (i32.ne (i32.load (i32.const 0)) (local.get $hsub)) (then unreachable))
      (if (i32.ne (i32.load (i32.const 4)) (i32.const 2 (; RETURNED ;))) (then unreachable))
      (if (i32.ne (i32.load (i32.const 24)) (i32.const 43)) (then unreachable))
      (call $waitable.join (local.get $hsub) (i32.const 0))
      (call $subtask.drop (local.get $hsub))
      (i32.const 42))
  )
  (core instance $main (instantiate $Main (with "" (instance
    (export "mem" (memory $memory "mem"))
    (export "future.new" (func $future.new))
    (export "future.write" (func $future.write))
    (export "holder" (func $holder'))
    (export "park" (func $park'))
    (export "ran" (func $ran'))
    (export "subtask.cancel" (func $subtask.cancel))
    (export "subtask.drop" (func $subtask.drop))
    (export "waitable.join" (func $waitable.join))
    (export "waitable-set.new" (func $waitable-set.new))
    (export "waitable-set.wait" (func $waitable-set.wait))))))
  (func (export "run") async (result u32) (canon lift (core func $main "run")))
)
(assert_return (invoke "run") (u32.const 42))
