;; 'subtask.cancel' resumes at most one thread: the implicit thread of the task
;; being cancelled, and only while that thread is parked in its `callback` event
;; loop; nothing else. Each case checks that the thread in question did not run,
;; whether the cancellation ends up BLOCKED or the targeted thread resolves it.

;; The implicit thread of a `callback` task that has already returned EXIT is
;; gone, so there is nothing for the cancellation to resume, even though the
;; task is still unresolved because an explicit thread is keeping it alive.
;; 'exiter' never blocks, so it has left its event loop by the time the caller
;; regains control.
(component
  (component $C
    (core module $Table (table (export "tbl") 1 funcref))
    (core instance $table (instantiate $Table))
    (core module $CM
      (import "" "tbl" (table $tbl 1 funcref))
      (import "" "task.return" (func $task.return (param i32)))
      (import "" "thread.new-indirect" (func $thread.new-indirect (param i32 i32) (result i32)))
      (import "" "thread.resume-later" (func $thread.resume-later (param i32)))

      ;; keeps the task alive once the implicit thread is gone, then resolves it
      (func $keeper (param i32) (call $task.return (i32.const 43)))
      (elem (table $tbl) (i32.const 0) func $keeper)

      (func (export "exiter") (result i32)
        (call $thread.resume-later (call $thread.new-indirect (i32.const 0) (i32.const 0)))
        (i32.const 0 (; EXIT ;)))
      (func (export "unreachable-cb") (param i32 i32 i32) (result i32)
        unreachable)
    )
    (core type $ThreadFT (func (param i32)))
    (alias core export $table "tbl" (core table $tbl))
    (canon task.return (result u32) (core func $task.return))
    (canon thread.new-indirect $ThreadFT (core table $tbl) (core func $thread.new-indirect))
    (canon thread.resume-later (core func $thread.resume-later))
    (core instance $cm (instantiate $CM (with "" (instance
      (export "tbl" (table $tbl))
      (export "task.return" (func $task.return))
      (export "thread.new-indirect" (func $thread.new-indirect))
      (export "thread.resume-later" (func $thread.resume-later))))))
    (func (export "exiter") async (result u32)
      (canon lift (core func $cm "exiter") async (callback (core func $cm "unreachable-cb"))))
  )
  (instance $c (instantiate $C))
  (core module $Memory (memory (export "mem") 1))
  (core instance $memory (instantiate $Memory))
  (canon lower (func $c "exiter") async (memory (core memory $memory "mem")) (core func $exiter'))
  (canon subtask.cancel async (core func $subtask.cancel))
  (canon subtask.drop (core func $subtask.drop))
  (canon waitable.join (core func $waitable.join))
  (canon waitable-set.new (core func $waitable-set.new))
  (canon waitable-set.wait (memory (core memory $memory "mem")) (core func $waitable-set.wait))

  (core module $Main
    (import "" "mem" (memory 1))
    (import "" "exiter" (func $exiter (param i32) (result i32)))
    (import "" "subtask.cancel" (func $subtask.cancel (param i32) (result i32)))
    (import "" "subtask.drop" (func $subtask.drop (param i32)))
    (import "" "waitable.join" (func $waitable.join (param i32 i32)))
    (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
    (import "" "waitable-set.wait" (func $waitable-set.wait (param i32 i32) (result i32)))
    (func (export "run") (result i32)
      (local $packed i32) (local $sub i32) (local $ws i32)
      (local.set $packed (call $exiter (i32.const 24)))
      (if (i32.ne (i32.and (local.get $packed) (i32.const 0xf)) (i32.const 1 (; STARTED ;)))
        (then unreachable))
      (local.set $sub (i32.shr_u (local.get $packed) (i32.const 4)))

      ;; nothing to resume: the implicit thread is gone and the explicit thread
      ;; is not it
      (if (i32.ne (call $subtask.cancel (local.get $sub)) (i32.const -1 (; BLOCKED ;)))
        (then unreachable))

      ;; the explicit thread resolves the task, never seeing the cancellation
      (local.set $ws (call $waitable-set.new))
      (call $waitable.join (local.get $sub) (local.get $ws))
      (if (i32.ne (call $waitable-set.wait (local.get $ws) (i32.const 0))
                  (i32.const 1 (; SUBTASK ;)))
        (then unreachable))
      (if (i32.ne (i32.load (i32.const 0)) (local.get $sub)) (then unreachable))
      (if (i32.ne (i32.load (i32.const 4)) (i32.const 2 (; RETURNED ;))) (then unreachable))
      (if (i32.ne (i32.load (i32.const 24)) (i32.const 43)) (then unreachable))
      (call $waitable.join (local.get $sub) (i32.const 0))
      (call $subtask.drop (local.get $sub))
      (i32.const 42))
  )
  (core instance $main (instantiate $Main (with "" (instance
    (export "mem" (memory $memory "mem"))
    (export "exiter" (func $exiter'))
    (export "subtask.cancel" (func $subtask.cancel))
    (export "subtask.drop" (func $subtask.drop))
    (export "waitable.join" (func $waitable.join))
    (export "waitable-set.new" (func $waitable-set.new))
    (export "waitable-set.wait" (func $waitable-set.wait))))))
  (func (export "run") async (result u32) (canon lift (core func $main "run")))
)
(assert_return (invoke "run") (u32.const 42))

;; Cancelling a task must not resume a ready thread that belongs to a different
;; task, whether that task lives in the same component instance as the cancelled
;; one or in another instance. $C is instantiated twice so that both hold a
;; 'worker' parked in its event loop with a pending FUTURE_READ event, ready to
;; run as soon as the caller writes its future. Cancelling 'stuck', which is
;; stackful and blocked and so neither cancellable nor ready, must leave both
;; workers exactly where they are.
(component
  (component $C
    (core module $Memory (memory (export "mem") 1))
    (core instance $memory (instantiate $Memory))
    (core module $CM
      (import "" "mem" (memory 1))
      (import "" "task.return" (func $task.return (param i32)))
      (import "" "future.read" (func $future.read (param i32 i32) (result i32)))
      (import "" "future.read-sync" (func $future.read-sync (param i32 i32) (result i32)))
      (import "" "waitable.join" (func $waitable.join (param i32 i32)))
      (import "" "waitable-set.new" (func $waitable-set.new (result i32)))

      ;; Parks in its event loop with a *pending* FUTURE_READ event, so its
      ;; thread is ready as soon as the caller writes the future.
      (func (export "worker") (param $futr i32) (result i32)
        (local $ws i32)
        (if (i32.ne (i32.const -1 (; BLOCKED ;))
                    (call $future.read (local.get $futr) (i32.const 16)))
          (then unreachable))
        (local.set $ws (call $waitable-set.new))
        (call $waitable.join (local.get $futr) (local.get $ws))
        (i32.or (i32.const 2 (; WAIT ;)) (i32.shl (local.get $ws) (i32.const 4))))
      (func (export "worker-cb") (param $event i32) (param i32 i32) (result i32)
        (if (i32.ne (local.get $event) (i32.const 4 (; FUTURE_READ ;)))
          (then unreachable))
        (call $task.return (i32.const 43))
        (i32.const 0 (; EXIT ;)))

      ;; The cancellation target: stackful, so never cancellable, and blocked
      ;; on a future nobody has written, so not ready either.
      (func (export "stuck") (param $futr i32)
        (if (i32.ne (i32.const 0 (; COMPLETED ;))
                    (call $future.read-sync (local.get $futr) (i32.const 16)))
          (then unreachable))
        (call $task.return (i32.const 44)))
    )
    (type $FT (future))
    (canon task.return (result u32) (core func $task.return))
    (canon future.read $FT async (memory (core memory $memory "mem")) (core func $future.read))
    (canon future.read $FT (memory (core memory $memory "mem")) (core func $future.read-sync))
    (canon waitable.join (core func $waitable.join))
    (canon waitable-set.new (core func $waitable-set.new))
    (core instance $cm (instantiate $CM (with "" (instance
      (export "mem" (memory $memory "mem"))
      (export "task.return" (func $task.return))
      (export "future.read" (func $future.read))
      (export "future.read-sync" (func $future.read-sync))
      (export "waitable.join" (func $waitable.join))
      (export "waitable-set.new" (func $waitable-set.new))))))
    (func (export "worker") async (param "fut" $FT) (result u32)
      (canon lift (core func $cm "worker") async (callback (core func $cm "worker-cb"))))
    (func (export "stuck") async (param "fut" $FT) (result u32)
      (canon lift (core func $cm "stuck") async))
  )
  (instance $c1 (instantiate $C))
  (instance $c2 (instantiate $C))
  (core module $Memory (memory (export "mem") 1))
  (core instance $memory (instantiate $Memory))
  (type $FT (future))
  (canon future.new $FT (core func $future.new))
  (canon future.write $FT async (memory (core memory $memory "mem")) (core func $future.write))
  (canon lower (func $c1 "worker") async (memory (core memory $memory "mem")) (core func $worker-same'))
  (canon lower (func $c2 "worker") async (memory (core memory $memory "mem")) (core func $worker-other'))
  (canon lower (func $c1 "stuck") async (memory (core memory $memory "mem")) (core func $stuck'))
  (canon subtask.cancel async (core func $subtask.cancel))
  (canon subtask.drop (core func $subtask.drop))
  (canon waitable.join (core func $waitable.join))
  (canon waitable-set.new (core func $waitable-set.new))
  (canon waitable-set.poll (memory (core memory $memory "mem")) (core func $waitable-set.poll))
  (canon waitable-set.wait (memory (core memory $memory "mem")) (core func $waitable-set.wait))

  (core module $Main
    (import "" "mem" (memory 1))
    (import "" "future.new" (func $future.new (result i64)))
    (import "" "future.write" (func $future.write (param i32 i32) (result i32)))
    (import "" "worker-same" (func $worker-same (param i32 i32) (result i32)))
    (import "" "worker-other" (func $worker-other (param i32 i32) (result i32)))
    (import "" "stuck" (func $stuck (param i32 i32) (result i32)))
    (import "" "subtask.cancel" (func $subtask.cancel (param i32) (result i32)))
    (import "" "subtask.drop" (func $subtask.drop (param i32)))
    (import "" "waitable.join" (func $waitable.join (param i32 i32)))
    (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
    (import "" "waitable-set.poll" (func $waitable-set.poll (param i32 i32) (result i32)))
    (import "" "waitable-set.wait" (func $waitable-set.wait (param i32 i32) (result i32)))

    ;; checks that a callee started and returns its subtask index
    (func $start (param $packed i32) (result i32)
      (if (i32.ne (i32.and (local.get $packed) (i32.const 0xf)) (i32.const 1 (; STARTED ;)))
        (then unreachable))
      (i32.shr_u (local.get $packed) (i32.const 4)))
    (func $ready (param $futw i32)
      (if (i32.ne (i32.const 0 (; COMPLETED ;))
                  (call $future.write (local.get $futw) (i32.const 16)))
        (then unreachable)))
    (func $watch (param $sub i32) (result i32)
      (local $set i32)
      (local.set $set (call $waitable-set.new))
      (call $waitable.join (local.get $sub) (local.get $set))
      (local.get $set))
    (func $assert-quiet (param $set i32)
      (if (i32.ne (call $waitable-set.poll (local.get $set) (i32.const 0))
                  (i32.const 0 (; NONE ;)))
        (then unreachable)))
    (func $await-returned (param $set i32) (param $sub i32) (param $retp i32) (param $expected i32)
      (if (i32.ne (call $waitable-set.wait (local.get $set) (i32.const 0))
                  (i32.const 1 (; SUBTASK ;)))
        (then unreachable))
      (if (i32.ne (i32.load (i32.const 0)) (local.get $sub)) (then unreachable))
      (if (i32.ne (i32.load (i32.const 4)) (i32.const 2 (; RETURNED ;))) (then unreachable))
      (if (i32.ne (i32.load (local.get $retp)) (local.get $expected)) (then unreachable))
      (call $waitable.join (local.get $sub) (i32.const 0))
      (call $subtask.drop (local.get $sub)))

    (func (export "run") (result i32)
      (local $ret64 i64)
      (local $same-r i32) (local $same-w i32)
      (local $other-r i32) (local $other-w i32)
      (local $stuck-r i32) (local $stuck-w i32)
      (local $same i32) (local $other i32) (local $stuck-sub i32)
      (local $same-set i32) (local $other-set i32) (local $stuck-set i32)

      (local.set $ret64 (call $future.new))
      (local.set $same-r (i32.wrap_i64 (local.get $ret64)))
      (local.set $same-w (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
      (local.set $ret64 (call $future.new))
      (local.set $other-r (i32.wrap_i64 (local.get $ret64)))
      (local.set $other-w (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
      (local.set $ret64 (call $future.new))
      (local.set $stuck-r (i32.wrap_i64 (local.get $ret64)))
      (local.set $stuck-w (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))

      ;; both workers park in their event loops, releasing their instances'
      ;; exclusive locks
      (local.set $same (call $start (call $worker-same (local.get $same-r) (i32.const 24))))
      (local.set $other (call $start (call $worker-other (local.get $other-r) (i32.const 28))))
      (local.set $stuck-sub (call $start (call $stuck (local.get $stuck-r) (i32.const 32))))

      ;; make both workers' threads ready without resuming them
      (call $ready (local.get $same-w))
      (call $ready (local.get $other-w))
      (local.set $same-set (call $watch (local.get $same)))
      (local.set $other-set (call $watch (local.get $other)))
      (call $assert-quiet (local.get $same-set))
      (call $assert-quiet (local.get $other-set))

      ;; stuck is neither cancellable nor ready, and both workers belong to
      ;; other tasks, so nothing is resumed
      (if (i32.ne (call $subtask.cancel (local.get $stuck-sub)) (i32.const -1 (; BLOCKED ;)))
        (then unreachable))
      (call $assert-quiet (local.get $same-set))
      (call $assert-quiet (local.get $other-set))

      ;; all three still finish normally once this task blocks
      (call $await-returned (local.get $same-set) (local.get $same) (i32.const 24) (i32.const 43))
      (call $await-returned (local.get $other-set) (local.get $other) (i32.const 28) (i32.const 43))
      (call $ready (local.get $stuck-w))
      (local.set $stuck-set (call $watch (local.get $stuck-sub)))
      (call $await-returned (local.get $stuck-set) (local.get $stuck-sub) (i32.const 32) (i32.const 44))
      (i32.const 42))
  )
  (core instance $main (instantiate $Main (with "" (instance
    (export "mem" (memory $memory "mem"))
    (export "future.new" (func $future.new))
    (export "future.write" (func $future.write))
    (export "worker-same" (func $worker-same'))
    (export "worker-other" (func $worker-other'))
    (export "stuck" (func $stuck'))
    (export "subtask.cancel" (func $subtask.cancel))
    (export "subtask.drop" (func $subtask.drop))
    (export "waitable.join" (func $waitable.join))
    (export "waitable-set.new" (func $waitable-set.new))
    (export "waitable-set.poll" (func $waitable-set.poll))
    (export "waitable-set.wait" (func $waitable-set.wait))))))
  (func (export "run") async (result u32) (canon lift (core func $main "run")))
)
(assert_return (invoke "run") (u32.const 42))

;; Test that a callback is not called while another thread is holding
;; the exclusive lock.
(component
  (component $C
    (core module $Memory (memory (export "mem") 1))
    (core instance $memory (instantiate $Memory))
    (core module $CM
      (import "" "mem" (memory 1))
      (import "" "task.return" (func $task.return (param i32)))
      (import "" "task.cancel" (func $task.cancel))
      (import "" "future.read" (func $future.read (param i32 i32) (result i32)))
      (import "" "waitable.join" (func $waitable.join (param i32 i32)))
      (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
      (import "" "waitable-set.wait" (func $waitable-set.wait (param i32 i32) (result i32)))

      ;; Parks in the event loop on a waitable set that never gets an event, so
      ;; only the delivery of a pending cancellation can wake this task which
      ;; cannot happen while the exclusive lock is held.
      (global $never (mut i32) (i32.const 0))
      (func $start (global.set $never (call $waitable-set.new)))
      (start $start)
      (func (export "park") (result i32)
        (i32.or (i32.const 2 (; WAIT ;)) (i32.shl (global.get $never) (i32.const 4))))
      (func (export "park-cb") (param $event i32) (param i32 i32) (result i32)
        (if (i32.ne (local.get $event) (i32.const 6 (; TASK_CANCELLED ;)))
          (then unreachable))
        (call $task.cancel)
        (i32.const 0 (; EXIT ;)))

      ;; Blocks holding the instance's exclusive lock for as long as it is
      ;; blocked. Once the caller writes the future, this task's thread is ready
      ;; but the lock is still held.
      (func (export "hold-lock") (param $futr i32) (result i32)
        (local $ws i32)
        (if (i32.ne (i32.const -1 (; BLOCKED ;))
                    (call $future.read (local.get $futr) (i32.const 0)))
          (then unreachable))
        (local.set $ws (call $waitable-set.new))
        (call $waitable.join (local.get $futr) (local.get $ws))
        (if (i32.ne (i32.const 4 (; FUTURE_READ ;))
                    (call $waitable-set.wait (local.get $ws) (i32.const 8)))
          (then unreachable))
        (call $task.return (i32.const 43))
        (i32.const 0 (; EXIT ;)))
      (func (export "unreachable-cb") (param i32 i32 i32) (result i32)
        unreachable)
    )
    (type $FT (future))
    (canon task.return (result u32) (core func $task.return))
    (canon task.cancel (core func $task.cancel))
    (canon future.read $FT async (memory (core memory $memory "mem")) (core func $future.read))
    (canon waitable.join (core func $waitable.join))
    (canon waitable-set.new (core func $waitable-set.new))
    (canon waitable-set.wait (memory (core memory $memory "mem")) (core func $waitable-set.wait))
    (core instance $cm (instantiate $CM (with "" (instance
      (export "mem" (memory $memory "mem"))
      (export "task.return" (func $task.return))
      (export "task.cancel" (func $task.cancel))
      (export "future.read" (func $future.read))
      (export "waitable.join" (func $waitable.join))
      (export "waitable-set.new" (func $waitable-set.new))
      (export "waitable-set.wait" (func $waitable-set.wait))))))
    (func (export "park") async
      (canon lift (core func $cm "park") async (callback (core func $cm "park-cb"))))
    (func (export "hold-lock") async (param "fut" $FT) (result u32)
      (canon lift (core func $cm "hold-lock") async (callback (core func $cm "unreachable-cb"))))
  )
  (instance $c (instantiate $C))
  (core module $Memory (memory (export "mem") 1))
  (core instance $memory (instantiate $Memory))
  (type $FT (future))
  (canon future.new $FT (core func $future.new))
  (canon future.write $FT (memory (core memory $memory "mem")) (core func $future.write))
  (canon lower (func $c "park") async (core func $park'))
  (canon lower (func $c "hold-lock") async (memory (core memory $memory "mem")) (core func $hold-lock'))
  (canon subtask.cancel async (core func $subtask.cancel-async))
  (canon subtask.drop (core func $subtask.drop))
  (canon waitable.join (core func $waitable.join))
  (canon waitable-set.new (core func $waitable-set.new))
  (canon waitable-set.poll (memory (core memory $memory "mem")) (core func $waitable-set.poll))
  (canon waitable-set.wait (memory (core memory $memory "mem")) (core func $waitable-set.wait))

  (core module $Main
    (import "" "mem" (memory 1))
    (import "" "future.new" (func $future.new (result i64)))
    (import "" "future.write" (func $future.write (param i32 i32) (result i32)))
    (import "" "park" (func $park (result i32)))
    (import "" "hold-lock" (func $hold-lock (param i32 i32) (result i32)))
    (import "" "subtask.cancel-async" (func $subtask.cancel-async (param i32) (result i32)))
    (import "" "subtask.drop" (func $subtask.drop (param i32)))
    (import "" "waitable.join" (func $waitable.join (param i32 i32)))
    (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
    (import "" "waitable-set.poll" (func $waitable-set.poll (param i32 i32) (result i32)))
    (import "" "waitable-set.wait" (func $waitable-set.wait (param i32 i32) (result i32)))
    (func (export "run") (result i32)
      (local $ret64 i64) (local $futr i32) (local $futw i32)
      (local $packed i32)
      (local $park-sub i32) (local $hold-sub i32)
      (local $park-ws i32) (local $hold-ws i32)

      ;; start "park"; returning WAIT releases the lock, so it is free here
      (local.set $packed (call $park))
      (if (i32.ne (i32.and (local.get $packed) (i32.const 0xf)) (i32.const 1 (; STARTED ;)))
        (then unreachable))
      (local.set $park-sub (i32.shr_u (local.get $packed) (i32.const 4)))

      ;; start hold-lock; it takes the lock and blocks while holding it
      (local.set $ret64 (call $future.new))
      (local.set $futr (i32.wrap_i64 (local.get $ret64)))
      (local.set $futw (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
      (local.set $packed (call $hold-lock (local.get $futr) (i32.const 24)))
      (if (i32.ne (i32.and (local.get $packed) (i32.const 0xf)) (i32.const 1 (; STARTED ;)))
        (then unreachable))
      (local.set $hold-sub (i32.shr_u (local.get $packed) (i32.const 4)))
      (local.set $hold-ws (call $waitable-set.new))
      (call $waitable.join (local.get $hold-sub) (local.get $hold-ws))

      ;; complete the read: hold-lock's thread is now ready, but it still
      ;; holds the lock and nothing has resumed it
      (if (i32.ne (i32.const 0 (; COMPLETED ;))
                  (call $future.write (local.get $futw) (i32.const 16)))
        (then unreachable))
      (if (i32.ne (call $waitable-set.poll (local.get $hold-ws) (i32.const 0))
                  (i32.const 0 (; NONE ;)))
        (then unreachable))

      ;; cancel park: its own thread is not ready while the lock is held, and
      ;; hold-lock's ready thread belongs to a different task, so nothing at
      ;; all is resumed
      (if (i32.ne (call $subtask.cancel-async (local.get $park-sub))
                  (i32.const -1 (; BLOCKED ;)))
        (then unreachable))
      (if (i32.ne (call $waitable-set.poll (local.get $hold-ws) (i32.const 0))
                  (i32.const 0 (; NONE ;)))
        (then unreachable))

      ;; blocking here lets hold-lock finish and release the lock
      (if (i32.ne (call $waitable-set.wait (local.get $hold-ws) (i32.const 0))
                  (i32.const 1 (; SUBTASK ;)))
        (then unreachable))
      (if (i32.ne (i32.load (i32.const 0)) (local.get $hold-sub))
        (then unreachable))
      (if (i32.ne (i32.load (i32.const 4)) (i32.const 2 (; RETURNED ;)))
        (then unreachable))
      (if (i32.ne (i32.load (i32.const 24)) (i32.const 43))
        (then unreachable))
      (call $waitable.join (local.get $hold-sub) (i32.const 0))
      (call $subtask.drop (local.get $hold-sub))

      ;; with the lock now free, blocking lets park receive the request
      (local.set $park-ws (call $waitable-set.new))
      (call $waitable.join (local.get $park-sub) (local.get $park-ws))
      (if (i32.ne (call $waitable-set.wait (local.get $park-ws) (i32.const 0))
                  (i32.const 1 (; SUBTASK ;)))
        (then unreachable))
      (if (i32.ne (i32.load (i32.const 0)) (local.get $park-sub))
        (then unreachable))
      (if (i32.ne (i32.load (i32.const 4)) (i32.const 4 (; CANCELLED_BEFORE_RETURNED ;)))
        (then unreachable))
      (call $waitable.join (local.get $park-sub) (i32.const 0))
      (call $subtask.drop (local.get $park-sub))
      (i32.const 42))
  )
  (core instance $main (instantiate $Main (with "" (instance
    (export "mem" (memory $memory "mem"))
    (export "future.new" (func $future.new))
    (export "future.write" (func $future.write))
    (export "park" (func $park'))
    (export "hold-lock" (func $hold-lock'))
    (export "subtask.cancel-async" (func $subtask.cancel-async))
    (export "subtask.drop" (func $subtask.drop))
    (export "waitable.join" (func $waitable.join))
    (export "waitable-set.new" (func $waitable-set.new))
    (export "waitable-set.poll" (func $waitable-set.poll))
    (export "waitable-set.wait" (func $waitable-set.wait))))))
  (func (export "run") async (result u32) (canon lift (core func $main "run")))
)
(assert_return (invoke "run") (u32.const 42))

;; Once the cancelled task's own callback thread has been resumed and the task
;; has resolved, 'subtask.cancel' returns without resuming anything else, even
;; though 'worker' has been sitting ready in its event loop the whole time.
(component
  (component $C
    (core module $Memory (memory (export "mem") 1))
    (core instance $memory (instantiate $Memory))
    (core module $CM
      (import "" "mem" (memory 1))
      (import "" "task.return" (func $task.return (param i32)))
      (import "" "task.cancel" (func $task.cancel))
      (import "" "future.read" (func $future.read (param i32 i32) (result i32)))
      (import "" "waitable.join" (func $waitable.join (param i32 i32)))
      (import "" "waitable-set.new" (func $waitable-set.new (result i32)))

      ;; ready before the cancel: parked in its event loop with a pending event
      (func (export "worker") (param $futr i32) (result i32)
        (local $ws i32)
        (if (i32.ne (i32.const -1 (; BLOCKED ;))
                    (call $future.read (local.get $futr) (i32.const 16)))
          (then unreachable))
        (local.set $ws (call $waitable-set.new))
        (call $waitable.join (local.get $futr) (local.get $ws))
        (i32.or (i32.const 2 (; WAIT ;)) (i32.shl (local.get $ws) (i32.const 4))))
      (func (export "worker-cb") (param $event i32) (param i32 i32) (result i32)
        (if (i32.ne (local.get $event) (i32.const 4 (; FUTURE_READ ;)))
          (then unreachable))
        (call $task.return (i32.const 43))
        (i32.const 0 (; EXIT ;)))

      ;; the cancellation target
      (func (export "park") (result i32)
        (i32.or (i32.const 2 (; WAIT ;))
                (i32.shl (call $waitable-set.new) (i32.const 4))))
      (func (export "park-cb") (param $event i32) (param i32 i32) (result i32)
        (if (i32.ne (local.get $event) (i32.const 6 (; TASK_CANCELLED ;)))
          (then unreachable))
        (call $task.cancel)
        (i32.const 0 (; EXIT ;)))
    )
    (type $FT (future))
    (canon task.return (result u32) (core func $task.return))
    (canon task.cancel (core func $task.cancel))
    (canon future.read $FT async (memory (core memory $memory "mem")) (core func $future.read))
    (canon waitable.join (core func $waitable.join))
    (canon waitable-set.new (core func $waitable-set.new))
    (core instance $cm (instantiate $CM (with "" (instance
      (export "mem" (memory $memory "mem"))
      (export "task.return" (func $task.return))
      (export "task.cancel" (func $task.cancel))
      (export "future.read" (func $future.read))
      (export "waitable.join" (func $waitable.join))
      (export "waitable-set.new" (func $waitable-set.new))))))
    (func (export "worker") async (param "fut" $FT) (result u32)
      (canon lift (core func $cm "worker") async (callback (core func $cm "worker-cb"))))
    (func (export "park") async
      (canon lift (core func $cm "park") async (callback (core func $cm "park-cb"))))
  )
  (instance $c (instantiate $C))
  (core module $Memory (memory (export "mem") 1))
  (core instance $memory (instantiate $Memory))
  (type $FT (future))
  (canon future.new $FT (core func $future.new))
  (canon future.write $FT async (memory (core memory $memory "mem")) (core func $future.write))
  (canon lower (func $c "worker") async (memory (core memory $memory "mem")) (core func $worker'))
  (canon lower (func $c "park") async (core func $park'))
  (canon subtask.cancel async (core func $subtask.cancel))
  (canon subtask.drop (core func $subtask.drop))
  (canon waitable.join (core func $waitable.join))
  (canon waitable-set.new (core func $waitable-set.new))
  (canon waitable-set.poll (memory (core memory $memory "mem")) (core func $waitable-set.poll))
  (canon waitable-set.wait (memory (core memory $memory "mem")) (core func $waitable-set.wait))

  (core module $Main
    (import "" "mem" (memory 1))
    (import "" "future.new" (func $future.new (result i64)))
    (import "" "future.write" (func $future.write (param i32 i32) (result i32)))
    (import "" "worker" (func $worker (param i32 i32) (result i32)))
    (import "" "park" (func $park (result i32)))
    (import "" "subtask.cancel" (func $subtask.cancel (param i32) (result i32)))
    (import "" "subtask.drop" (func $subtask.drop (param i32)))
    (import "" "waitable.join" (func $waitable.join (param i32 i32)))
    (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
    (import "" "waitable-set.poll" (func $waitable-set.poll (param i32 i32) (result i32)))
    (import "" "waitable-set.wait" (func $waitable-set.wait (param i32 i32) (result i32)))
    (func (export "run") (result i32)
      (local $ret64 i64) (local $futr i32) (local $futw i32)
      (local $packed i32) (local $wsub i32) (local $psub i32) (local $ws i32)
      (local.set $ret64 (call $future.new))
      (local.set $futr (i32.wrap_i64 (local.get $ret64)))
      (local.set $futw (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))

      (local.set $packed (call $worker (local.get $futr) (i32.const 24)))
      (if (i32.ne (i32.and (local.get $packed) (i32.const 0xf)) (i32.const 1 (; STARTED ;)))
        (then unreachable))
      (local.set $wsub (i32.shr_u (local.get $packed) (i32.const 4)))
      (local.set $packed (call $park))
      (if (i32.ne (i32.and (local.get $packed) (i32.const 0xf)) (i32.const 1 (; STARTED ;)))
        (then unreachable))
      (local.set $psub (i32.shr_u (local.get $packed) (i32.const 4)))

      ;; worker's thread is now ready, but nothing has resumed it
      (if (i32.ne (i32.const 0 (; COMPLETED ;))
                  (call $future.write (local.get $futw) (i32.const 16)))
        (then unreachable))
      (local.set $ws (call $waitable-set.new))
      (call $waitable.join (local.get $wsub) (local.get $ws))
      (if (i32.ne (call $waitable-set.poll (local.get $ws) (i32.const 0))
                  (i32.const 0 (; NONE ;)))
        (then unreachable))

      ;; park is resumed and resolves eagerly, but worker stays put
      (if (i32.ne (call $subtask.cancel (local.get $psub))
                  (i32.const 4 (; CANCELLED_BEFORE_RETURNED ;)))
        (then unreachable))
      (if (i32.ne (call $waitable-set.poll (local.get $ws) (i32.const 0))
                  (i32.const 0 (; NONE ;)))
        (then unreachable))
      (call $subtask.drop (local.get $psub))

      ;; worker still runs once this task blocks
      (if (i32.ne (call $waitable-set.wait (local.get $ws) (i32.const 0))
                  (i32.const 1 (; SUBTASK ;)))
        (then unreachable))
      (if (i32.ne (i32.load (i32.const 0)) (local.get $wsub)) (then unreachable))
      (if (i32.ne (i32.load (i32.const 4)) (i32.const 2 (; RETURNED ;))) (then unreachable))
      (if (i32.ne (i32.load (i32.const 24)) (i32.const 43)) (then unreachable))
      (call $waitable.join (local.get $wsub) (i32.const 0))
      (call $subtask.drop (local.get $wsub))
      (i32.const 42))
  )
  (core instance $main (instantiate $Main (with "" (instance
    (export "mem" (memory $memory "mem"))
    (export "future.new" (func $future.new))
    (export "future.write" (func $future.write))
    (export "worker" (func $worker'))
    (export "park" (func $park'))
    (export "subtask.cancel" (func $subtask.cancel))
    (export "subtask.drop" (func $subtask.drop))
    (export "waitable.join" (func $waitable.join))
    (export "waitable-set.new" (func $waitable-set.new))
    (export "waitable-set.poll" (func $waitable-set.poll))
    (export "waitable-set.wait" (func $waitable-set.wait))))))
  (func (export "run") async (result u32) (canon lift (core func $main "run")))
)
(assert_return (invoke "run") (u32.const 42))

;; A thread made ready by the resumed callback itself, from inside the
;; cancellation, is not resumed either: 'subtask.cancel' returns as soon as the
;; callback is done. Yielding afterwards lets the host schedule it as it would
;; any other ready thread.
(component
  (component $C
    (core module $Table (table (export "tbl") 1 funcref))
    (core instance $table (instantiate $Table))
    (core module $CM
      (import "" "tbl" (table $tbl 1 funcref))
      (import "" "task.cancel" (func $task.cancel))
      (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
      (import "" "thread.new-indirect" (func $thread.new-indirect (param i32 i32) (result i32)))
      (import "" "thread.resume-later" (func $thread.resume-later (param i32)))

      (global $spawned-ran (mut i32) (i32.const 0))
      (func $spawned (param i32) (global.set $spawned-ran (i32.const 1)))
      (elem (table $tbl) (i32.const 0) func $spawned)
      (func (export "ran") (result i32) (global.get $spawned-ran))

      (func (export "park") (result i32)
        (i32.or (i32.const 2 (; WAIT ;))
                (i32.shl (call $waitable-set.new) (i32.const 4))))
      (func (export "park-cb") (param $event i32) (param i32 i32) (result i32)
        (if (i32.ne (local.get $event) (i32.const 6 (; TASK_CANCELLED ;)))
          (then unreachable))
        ;; make a fresh thread ready from inside the cancellation itself
        (call $thread.resume-later (call $thread.new-indirect (i32.const 0) (i32.const 0)))
        (call $task.cancel)
        (i32.const 0 (; EXIT ;)))
    )
    (core type $ThreadFT (func (param i32)))
    (alias core export $table "tbl" (core table $tbl))
    (canon task.cancel (core func $task.cancel))
    (canon waitable-set.new (core func $waitable-set.new))
    (canon thread.new-indirect $ThreadFT (core table $tbl) (core func $thread.new-indirect))
    (canon thread.resume-later (core func $thread.resume-later))
    (core instance $cm (instantiate $CM (with "" (instance
      (export "tbl" (table $tbl))
      (export "task.cancel" (func $task.cancel))
      (export "waitable-set.new" (func $waitable-set.new))
      (export "thread.new-indirect" (func $thread.new-indirect))
      (export "thread.resume-later" (func $thread.resume-later))))))
    (func (export "park") async
      (canon lift (core func $cm "park") async (callback (core func $cm "park-cb"))))
    (func (export "ran") (result u32) (canon lift (core func $cm "ran")))
  )
  (instance $c (instantiate $C))
  (canon lower (func $c "park") async (core func $park'))
  (canon lower (func $c "ran") (core func $ran'))
  (canon subtask.cancel async (core func $subtask.cancel))
  (canon subtask.drop (core func $subtask.drop))
  (canon thread.yield (core func $thread.yield))

  (core module $Main
    (import "" "park" (func $park (result i32)))
    (import "" "ran" (func $ran (result i32)))
    (import "" "subtask.cancel" (func $subtask.cancel (param i32) (result i32)))
    (import "" "subtask.drop" (func $subtask.drop (param i32)))
    (import "" "thread.yield" (func $thread.yield (result i32)))
    (func (export "run") (result i32)
      (local $packed i32) (local $sub i32) (local $i i32)
      (local.set $packed (call $park))
      (if (i32.ne (i32.and (local.get $packed) (i32.const 0xf)) (i32.const 1 (; STARTED ;)))
        (then unreachable))
      (local.set $sub (i32.shr_u (local.get $packed) (i32.const 4)))
      (if (i32.ne (call $subtask.cancel (local.get $sub))
                  (i32.const 4 (; CANCELLED_BEFORE_RETURNED ;)))
        (then unreachable))
      (if (call $ran) (then unreachable))
      (call $subtask.drop (local.get $sub))

      ;; yielding hands the deferred thread to the host, which runs it
      (block $done
        (loop $again
          (br_if $done (call $ran))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (if (i32.gt_u (local.get $i) (i32.const 32)) (then unreachable))
          (drop (call $thread.yield))
          (br $again)))
      (i32.const 42))
  )
  (core instance $main (instantiate $Main (with "" (instance
    (export "park" (func $park'))
    (export "ran" (func $ran'))
    (export "subtask.cancel" (func $subtask.cancel))
    (export "subtask.drop" (func $subtask.drop))
    (export "thread.yield" (func $thread.yield))))))
  (func (export "run") async (result u32) (canon lift (core func $main "run")))
)
(assert_return (invoke "run") (u32.const 42))
