;; Tests the `stream.forward` and `future.forward` built-ins.

(component definition $Tester
  (core module $Memory (memory (export "mem") 1))
  (core instance $memory (instantiate $Memory))
  (core module $M
    (import "" "mem" (memory 1))
    (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
    (import "" "waitable-set.poll" (func $waitable-set.poll (param i32 i32) (result i32)))
    (import "" "waitable.join" (func $waitable.join (param i32 i32)))
    (import "" "stream.new" (func $stream.new (result i64)))
    (import "" "stream.read" (func $stream.read (param i32 i32 i32) (result i32)))
    (import "" "stream.write" (func $stream.write (param i32 i32 i32) (result i32)))
    (import "" "stream.cancel-read" (func $stream.cancel-read (param i32) (result i32)))
    (import "" "stream.cancel-write" (func $stream.cancel-write (param i32) (result i32)))
    (import "" "stream.drop-readable" (func $stream.drop-readable (param i32)))
    (import "" "stream.drop-writable" (func $stream.drop-writable (param i32)))
    (import "" "stream.forward" (func $stream.forward (param i32 i32)))
    (import "" "stream.forward-u32" (func $stream.forward-u32 (param i32 i32)))
    (import "" "stream.new-e" (func $stream.new-e (result i64)))
    (import "" "stream.read-e" (func $stream.read-e (param i32 i32 i32) (result i32)))
    (import "" "stream.write-e" (func $stream.write-e (param i32 i32 i32) (result i32)))
    (import "" "stream.forward-e" (func $stream.forward-e (param i32 i32)))
    (import "" "future.new" (func $future.new (result i64)))
    (import "" "future.read" (func $future.read (param i32 i32) (result i32)))
    (import "" "future.write" (func $future.write (param i32 i32) (result i32)))
    (import "" "future.drop-readable" (func $future.drop-readable (param i32)))
    (import "" "future.drop-writable" (func $future.drop-writable (param i32)))
    (import "" "future.forward" (func $future.forward (param i32 i32)))

    ;; The three streams/futures used by the tests below are named A, B and C
    ;; and their ends are kept in globals so that each test can stay readable.
    ;; A fresh $Tester instance is created before every invoke, so the handle
    ;; indices allocated by the $new-* helpers are deterministic: 1,2 for A,
    ;; 3,4 for B and 5,6 for C.
    (global $rA (mut i32) (i32.const 0))
    (global $wA (mut i32) (i32.const 0))
    (global $rB (mut i32) (i32.const 0))
    (global $wB (mut i32) (i32.const 0))
    (global $rC (mut i32) (i32.const 0))
    (global $wC (mut i32) (i32.const 0))

    (func $new-a
      (local $ret64 i64)
      (local.set $ret64 (call $stream.new))
      (global.set $rA (i32.wrap_i64 (local.get $ret64)))
      (global.set $wA (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
    )
    (func $new-b
      (local $ret64 i64)
      (local.set $ret64 (call $stream.new))
      (global.set $rB (i32.wrap_i64 (local.get $ret64)))
      (global.set $wB (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
    )
    (func $new-c
      (local $ret64 i64)
      (local.set $ret64 (call $stream.new))
      (global.set $rC (i32.wrap_i64 (local.get $ret64)))
      (global.set $wC (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
    )
    (func $fnew-a
      (local $ret64 i64)
      (local.set $ret64 (call $future.new))
      (global.set $rA (i32.wrap_i64 (local.get $ret64)))
      (global.set $wA (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
    )
    (func $fnew-b
      (local $ret64 i64)
      (local.set $ret64 (call $future.new))
      (global.set $rB (i32.wrap_i64 (local.get $ret64)))
      (global.set $wB (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
    )
    (func $fnew-c
      (local $ret64 i64)
      (local.set $ret64 (call $future.new))
      (global.set $rC (i32.wrap_i64 (local.get $ret64)))
      (global.set $wC (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
    )
    (func $enew-a
      (local $ret64 i64)
      (local.set $ret64 (call $stream.new-e))
      (global.set $rA (i32.wrap_i64 (local.get $ret64)))
      (global.set $wA (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
    )
    (func $enew-b
      (local $ret64 i64)
      (local.set $ret64 (call $stream.new-e))
      (global.set $rB (i32.wrap_i64 (local.get $ret64)))
      (global.set $wB (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
    )

    ;; the merged stream is usable in both arrival orders
    (func (export "forward-then-write-then-read") (result i32)
      (local $ret i32)
      (call $new-a)
      (call $new-b)
      (call $stream.forward (global.get $rA) (global.get $wB))
      (i32.store (i32.const 0) (i32.const 0x04030201))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (i32.const 0x04030201) (i32.load (i32.const 8)))
        (then unreachable))
      (i32.const 42)
    )
    (func (export "forward-then-read-then-write") (result i32)
      (local $ret i32)
      (call $new-a)
      (call $new-b)
      (call $stream.forward (global.get $rA) (global.get $wB))
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (i32.store (i32.const 0) (i32.const 0x04030201))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (i32.const 0x04030201) (i32.load (i32.const 8)))
        (then unreachable))
      (i32.const 42)
    )

    ;; a copy that was already pending when the forward happened is carried
    ;; over onto the merged stream
    (func (export "read-then-forward-then-write") (result i32)
      (local $ret i32) (local $ws i32)
      (call $new-a)
      (call $new-b)
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $stream.forward (global.get $rA) (global.get $wB))
      (i32.store (i32.const 0) (i32.const 0x04030201))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (i32.const 0x04030201) (i32.load (i32.const 8)))
        (then unreachable))
      (local.set $ws (call $waitable-set.new))
      (call $waitable.join (global.get $rB) (local.get $ws))
      (local.set $ret (call $waitable-set.poll (local.get $ws) (i32.const 32)))
      (if (i32.ne (i32.const 2 (; STREAM_READ ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (global.get $rB) (i32.load (i32.const 32)))
        (then unreachable))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (i32.load (i32.const 36)))
        (then unreachable))
      (i32.const 42)
    )

    ;; both sides are blocked before the forward, so the forward itself
    ;; performs the rendezvous
    (func (export "rendezvous-during-forward") (result i32)
      (local $ret i32) (local $ws1 i32) (local $ws2 i32)
      (call $new-a)
      (call $new-b)
      (i32.store (i32.const 0) (i32.const 0x04030201))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $stream.forward (global.get $rA) (global.get $wB))
      (if (i32.ne (i32.const 0x04030201) (i32.load (i32.const 8)))
        (then unreachable))
      (local.set $ws1 (call $waitable-set.new))
      (local.set $ws2 (call $waitable-set.new))
      (call $waitable.join (global.get $wA) (local.get $ws1))
      (call $waitable.join (global.get $rB) (local.get $ws2))
      (local.set $ret (call $waitable-set.poll (local.get $ws1) (i32.const 32)))
      (if (i32.ne (i32.const 3 (; STREAM_WRITE ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (global.get $wA) (i32.load (i32.const 32)))
        (then unreachable))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (i32.load (i32.const 36)))
        (then unreachable))
      (local.set $ret (call $waitable-set.poll (local.get $ws2) (i32.const 40)))
      (if (i32.ne (i32.const 2 (; STREAM_READ ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (global.get $rB) (i32.load (i32.const 40)))
        (then unreachable))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (i32.load (i32.const 44)))
        (then unreachable))
      (i32.const 42)
    )

    ;; the destination's readable end may already be in a waitable set when
    ;; the forward happens, and the carried-over read must still be reported
    ;; through it
    (func (export "pending-read-in-set-before-forward") (result i32)
      (local $ret i32) (local $ws i32)
      (call $new-a)
      (call $new-b)
      (local.set $ws (call $waitable-set.new))
      (call $waitable.join (global.get $rB) (local.get $ws))
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $stream.forward (global.get $rA) (global.get $wB))
      (i32.store (i32.const 0) (i32.const 0x04030201))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $waitable-set.poll (local.get $ws) (i32.const 32)))
      (if (i32.ne (i32.const 2 (; STREAM_READ ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (global.get $rB) (i32.load (i32.const 32)))
        (then unreachable))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (i32.load (i32.const 36)))
        (then unreachable))
      (if (i32.ne (i32.const 0x04030201) (i32.load (i32.const 8)))
        (then unreachable))
      (i32.const 42)
    )

    ;; discarding A's readable end and B's writable end must not look like a
    ;; drop to the two ends that survive
    (func (export "no-event-from-forward") (result i32)
      (local $ret i32) (local $ws i32)
      (call $new-a)
      (call $new-b)
      (local.set $ws (call $waitable-set.new))
      (call $waitable.join (global.get $wA) (local.get $ws))
      (call $waitable.join (global.get $rB) (local.get $ws))
      (call $stream.forward (global.get $rA) (global.get $wB))
      (local.set $ret (call $waitable-set.poll (local.get $ws) (i32.const 32)))
      (if (i32.ne (i32.const 0 (; NONE ;)) (local.get $ret))
        (then unreachable))
      (i32.store (i32.const 0) (i32.const 0x04030201))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $waitable-set.poll (local.get $ws) (i32.const 32)))
      (if (i32.ne (i32.const 3 (; STREAM_WRITE ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (global.get $wA) (i32.load (i32.const 32)))
        (then unreachable))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (i32.load (i32.const 36)))
        (then unreachable))
      (local.set $ret (call $waitable-set.poll (local.get $ws) (i32.const 32)))
      (if (i32.ne (i32.const 0 (; NONE ;)) (local.get $ret))
        (then unreachable))
      (i32.const 42)
    )

    ;; a zero-length readiness read or write is carried over just like a real
    ;; one and completes with 0 elements once the other end shows up
    (func (export "zero-length-read-carried-over") (result i32)
      (local $ret i32) (local $ws i32)
      (call $new-a)
      (call $new-b)
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 0) (i32.const 0)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $stream.forward (global.get $rA) (global.get $wB))
      (local.set $ws (call $waitable-set.new))
      (call $waitable.join (global.get $rB) (local.get $ws))
      (i32.store (i32.const 0) (i32.const 0x04030201))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $waitable-set.poll (local.get $ws) (i32.const 32)))
      (if (i32.ne (i32.const 2 (; STREAM_READ ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (global.get $rB) (i32.load (i32.const 32)))
        (then unreachable))
      (if (i32.ne (i32.const 0x0 (; COMPLETED=0 | (0<<4) ;)) (i32.load (i32.const 36)))
        (then unreachable))
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (i32.const 0x04030201) (i32.load (i32.const 8)))
        (then unreachable))
      (i32.const 42)
    )
    (func (export "zero-length-write-then-forward") (result i32)
      (local $ret i32) (local $ws i32)
      (call $new-a)
      (call $new-b)
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 0)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $stream.forward (global.get $rA) (global.get $wB))
      (local.set $ws (call $waitable-set.new))
      (call $waitable.join (global.get $wA) (local.get $ws))
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $waitable-set.poll (local.get $ws) (i32.const 32)))
      (if (i32.ne (i32.const 3 (; STREAM_WRITE ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (global.get $wA) (i32.load (i32.const 32)))
        (then unreachable))
      (if (i32.ne (i32.const 0x0 (; COMPLETED=0 | (0<<4) ;)) (i32.load (i32.const 36)))
        (then unreachable))
      (i32.store (i32.const 0) (i32.const 0x04030201))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (i32.const 0x04030201) (i32.load (i32.const 8)))
        (then unreachable))
      (i32.const 42)
    )

    ;; drop propagation in both directions
    (func (export "dest-reader-dropped-before-forward") (result i32)
      (local $ret i32)
      (call $new-a)
      (call $new-b)
      (call $stream.drop-readable (global.get $rB))
      (call $stream.forward (global.get $rA) (global.get $wB))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const 0x1 (; DROPPED=1 | (0<<4) ;)) (local.get $ret))
        (then unreachable))
      (call $stream.drop-writable (global.get $wA))
      (i32.const 42)
    )
    (func (export "dest-reader-dropped-before-forward-blocked-writer") (result i32)
      (local $ret i32) (local $ws i32)
      (call $new-a)
      (call $new-b)
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $stream.drop-readable (global.get $rB))
      (local.set $ws (call $waitable-set.new))
      (call $waitable.join (global.get $wA) (local.get $ws))
      (call $stream.forward (global.get $rA) (global.get $wB))
      (local.set $ret (call $waitable-set.poll (local.get $ws) (i32.const 32)))
      (if (i32.ne (i32.const 3 (; STREAM_WRITE ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (global.get $wA) (i32.load (i32.const 32)))
        (then unreachable))
      (if (i32.ne (i32.const 0x1 (; DROPPED=1 | (0<<4) ;)) (i32.load (i32.const 36)))
        (then unreachable))
      (call $stream.drop-writable (global.get $wA))
      (i32.const 42)
    )
    (func (export "dest-reader-dropped-after-forward") (result i32)
      (local $ret i32) (local $ws i32)
      (call $new-a)
      (call $new-b)
      (call $stream.forward (global.get $rA) (global.get $wB))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (local.set $ws (call $waitable-set.new))
      (call $waitable.join (global.get $wA) (local.get $ws))
      (call $stream.drop-readable (global.get $rB))
      (local.set $ret (call $waitable-set.poll (local.get $ws) (i32.const 32)))
      (if (i32.ne (i32.const 3 (; STREAM_WRITE ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (global.get $wA) (i32.load (i32.const 32)))
        (then unreachable))
      (if (i32.ne (i32.const 0x1 (; DROPPED=1 | (0<<4) ;)) (i32.load (i32.const 36)))
        (then unreachable))
      (i32.const 42)
    )
    (func (export "src-writer-dropped-before-forward") (result i32)
      (local $ret i32)
      (call $new-a)
      (call $new-b)
      (call $stream.drop-writable (global.get $wA))
      (call $stream.forward (global.get $rA) (global.get $wB))
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const 0x1 (; DROPPED=1 | (0<<4) ;)) (local.get $ret))
        (then unreachable))
      (call $stream.drop-readable (global.get $rB))
      (i32.const 42)
    )
    (func (export "src-writer-dropped-after-forward") (result i32)
      (local $ret i32) (local $ws i32)
      (call $new-a)
      (call $new-b)
      (call $stream.forward (global.get $rA) (global.get $wB))
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (local.set $ws (call $waitable-set.new))
      (call $waitable.join (global.get $rB) (local.get $ws))
      (call $stream.drop-writable (global.get $wA))
      (local.set $ret (call $waitable-set.poll (local.get $ws) (i32.const 32)))
      (if (i32.ne (i32.const 2 (; STREAM_READ ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (global.get $rB) (i32.load (i32.const 32)))
        (then unreachable))
      (if (i32.ne (i32.const 0x1 (; DROPPED=1 | (0<<4) ;)) (i32.load (i32.const 36)))
        (then unreachable))
      (i32.const 42)
    )

    ;; cancellation after forward
    (func (export "cancel-carried-over-read") (result i32)
      (local $ret i32)
      (call $new-a)
      (call $new-b)
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $stream.forward (global.get $rA) (global.get $wB))
      (local.set $ret (call $stream.cancel-read (global.get $rB)))
      (if (i32.ne (i32.const 0x2 (; CANCELLED=2 | (0<<4) ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (i32.store (i32.const 0) (i32.const 0x04030201))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (i32.const 0x04030201) (i32.load (i32.const 8)))
        (then unreachable))
      (i32.const 42)
    )

    ;; self-loop
    (func (export "self-forward") (result i32)
      (call $new-a)
      (if (i32.ne (i32.const 1) (global.get $rA))
        (then unreachable))
      (if (i32.ne (i32.const 2) (global.get $wA))
        (then unreachable))
      (call $stream.forward (global.get $rA) (global.get $wA))
      (call $new-b)
      (if (i32.ne (i32.const 2) (global.get $rB))
        (then unreachable))
      (if (i32.ne (i32.const 1) (global.get $wB))
        (then unreachable))
      (i32.const 42)
    )

    ;; A absorbs B, then C absorbs A: one stream from C's writer to B's reader
    (func (export "forward-chain") (result i32)
      (local $ret i32)
      (call $new-a)
      (call $new-b)
      (call $new-c)
      (call $stream.forward (global.get $rA) (global.get $wB))
      (call $stream.forward (global.get $rC) (global.get $wA))
      (i32.store (i32.const 0) (i32.const 0x04030201))
      (local.set $ret (call $stream.write (global.get $wC) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (i32.const 0x04030201) (i32.load (i32.const 8)))
        (then unreachable))
      (i32.const 42)
    )

    ;; forwarding A into B and then B's (now-shared) readable end back into
    ;; A's writable end degenerates into the self-loop case, so no cycle can
    ;; be built and there is nothing left to trap on
    (func (export "forward-cycle") (result i32)
      (call $new-a)
      (call $new-b)
      (call $stream.forward (global.get $rA) (global.get $wB))
      (call $stream.forward (global.get $rB) (global.get $wA))
      (call $new-c)
      (if (i32.ne (i32.const 2) (global.get $rC))
        (then unreachable))
      (if (i32.ne (i32.const 3) (global.get $wC))
        (then unreachable))
      (i32.const 42)
    )

    ;; future versions of all of the above
    (func (export "future-forward-then-write-then-read") (result i32)
      (local $ret i32)
      (call $fnew-a)
      (call $fnew-b)
      (call $future.forward (global.get $rA) (global.get $wB))
      (i32.store8 (i32.const 0) (i32.const 0x5a))
      (local.set $ret (call $future.write (global.get $wA) (i32.const 0)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $future.read (global.get $rB) (i32.const 8)))
      (if (i32.ne (i32.const 0 (; COMPLETED ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (i32.const 0x5a) (i32.load8_u (i32.const 8)))
        (then unreachable))
      (i32.const 42)
    )
    (func (export "future-forward-read-then-write") (result i32)
      (local $ret i32) (local $ws i32)
      (call $fnew-a)
      (call $fnew-b)
      (local.set $ret (call $future.read (global.get $rB) (i32.const 8)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $future.forward (global.get $rA) (global.get $wB))
      (i32.store8 (i32.const 0) (i32.const 0x5a))
      (local.set $ret (call $future.write (global.get $wA) (i32.const 0)))
      (if (i32.ne (i32.const 0 (; COMPLETED ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (i32.const 0x5a) (i32.load8_u (i32.const 8)))
        (then unreachable))
      (local.set $ws (call $waitable-set.new))
      (call $waitable.join (global.get $rB) (local.get $ws))
      (local.set $ret (call $waitable-set.poll (local.get $ws) (i32.const 32)))
      (if (i32.ne (i32.const 4 (; FUTURE_READ ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (global.get $rB) (i32.load (i32.const 32)))
        (then unreachable))
      (if (i32.ne (i32.const 0 (; COMPLETED ;)) (i32.load (i32.const 36)))
        (then unreachable))
      (i32.const 42)
    )
    (func (export "future-rendezvous-during-forward") (result i32)
      (local $ret i32) (local $ws1 i32) (local $ws2 i32)
      (call $fnew-a)
      (call $fnew-b)
      (i32.store8 (i32.const 0) (i32.const 0x5a))
      (local.set $ret (call $future.write (global.get $wA) (i32.const 0)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $future.read (global.get $rB) (i32.const 8)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $future.forward (global.get $rA) (global.get $wB))
      (if (i32.ne (i32.const 0x5a) (i32.load8_u (i32.const 8)))
        (then unreachable))
      (local.set $ws1 (call $waitable-set.new))
      (local.set $ws2 (call $waitable-set.new))
      (call $waitable.join (global.get $wA) (local.get $ws1))
      (call $waitable.join (global.get $rB) (local.get $ws2))
      (local.set $ret (call $waitable-set.poll (local.get $ws1) (i32.const 32)))
      (if (i32.ne (i32.const 5 (; FUTURE_WRITE ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (global.get $wA) (i32.load (i32.const 32)))
        (then unreachable))
      (if (i32.ne (i32.const 0 (; COMPLETED ;)) (i32.load (i32.const 36)))
        (then unreachable))
      (local.set $ret (call $waitable-set.poll (local.get $ws2) (i32.const 40)))
      (if (i32.ne (i32.const 4 (; FUTURE_READ ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (global.get $rB) (i32.load (i32.const 40)))
        (then unreachable))
      (if (i32.ne (i32.const 0 (; COMPLETED ;)) (i32.load (i32.const 44)))
        (then unreachable))
      (call $future.drop-writable (global.get $wA))
      (i32.const 42)
    )
    (func (export "future-forward-dest-reader-dropped") (result i32)
      (local $ret i32)
      (call $fnew-a)
      (call $fnew-b)
      (call $future.drop-readable (global.get $rB))
      (call $future.forward (global.get $rA) (global.get $wB))
      (local.set $ret (call $future.write (global.get $wA) (i32.const 0)))
      (if (i32.ne (i32.const 1 (; DROPPED ;)) (local.get $ret))
        (then unreachable))
      (call $future.drop-writable (global.get $wA))
      (i32.const 42)
    )
    (func (export "future-forward-dest-reader-dropped-blocked-writer") (result i32)
      (local $ret i32) (local $ws i32)
      (call $fnew-a)
      (call $fnew-b)
      (i32.store8 (i32.const 0) (i32.const 0x5a))
      (local.set $ret (call $future.write (global.get $wA) (i32.const 0)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $future.drop-readable (global.get $rB))
      (local.set $ws (call $waitable-set.new))
      (call $waitable.join (global.get $wA) (local.get $ws))
      (call $future.forward (global.get $rA) (global.get $wB))
      (local.set $ret (call $waitable-set.poll (local.get $ws) (i32.const 32)))
      (if (i32.ne (i32.const 5 (; FUTURE_WRITE ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (global.get $wA) (i32.load (i32.const 32)))
        (then unreachable))
      (if (i32.ne (i32.const 1 (; DROPPED ;)) (i32.load (i32.const 36)))
        (then unreachable))
      (call $future.drop-writable (global.get $wA))
      (i32.const 42)
    )
    (func (export "future-forward-discards-unwritten-writer") (result i32)
      (local $ret i32)
      (call $fnew-a)
      (call $fnew-b)
      (call $future.forward (global.get $rA) (global.get $wB))
      (i32.store8 (i32.const 0) (i32.const 0x5a))
      (local.set $ret (call $future.write (global.get $wA) (i32.const 0)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $future.read (global.get $rB) (i32.const 8)))
      (if (i32.ne (i32.const 0 (; COMPLETED ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (i32.const 0x5a) (i32.load8_u (i32.const 8)))
        (then unreachable))
      (i32.const 42)
    )
    (func (export "future-self-forward") (result i32)
      (call $fnew-a)
      (if (i32.ne (i32.const 1) (global.get $rA))
        (then unreachable))
      (if (i32.ne (i32.const 2) (global.get $wA))
        (then unreachable))
      (call $future.forward (global.get $rA) (global.get $wA))
      (call $fnew-b)
      (if (i32.ne (i32.const 2) (global.get $rB))
        (then unreachable))
      (if (i32.ne (i32.const 1) (global.get $wB))
        (then unreachable))
      (i32.const 42)
    )
    (func (export "future-forward-chain") (result i32)
      (local $ret i32)
      (call $fnew-a)
      (call $fnew-b)
      (call $fnew-c)
      (call $future.forward (global.get $rA) (global.get $wB))
      (call $future.forward (global.get $rC) (global.get $wA))
      (i32.store8 (i32.const 0) (i32.const 0x5a))
      (local.set $ret (call $future.write (global.get $wC) (i32.const 0)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $future.read (global.get $rB) (i32.const 8)))
      (if (i32.ne (i32.const 0 (; COMPLETED ;)) (local.get $ret))
        (then unreachable))
      (if (i32.ne (i32.const 0x5a) (i32.load8_u (i32.const 8)))
        (then unreachable))
      (i32.const 42)
    )

    ;; an empty element type forwards just like any other
    (func (export "empty-element-type") (result i32)
      (local $ret i32)
      (call $enew-a)
      (call $enew-b)
      (call $stream.forward-e (global.get $rA) (global.get $wB))
      (local.set $ret (call $stream.write-e (global.get $wA) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $stream.read-e (global.get $rB) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (local.get $ret))
        (then unreachable))
      (i32.const 42)
    )

    ;; trap conditions

    (func (export "trap-swapped-args")
      (call $new-a)
      (call $new-b)
      (call $stream.forward (global.get $wA) (global.get $rB))
      unreachable
    )
    (func (export "trap-type-mismatch")
      (call $new-a)
      (call $new-b)
      (call $stream.forward-u32 (global.get $rA) (global.get $wB))
      unreachable
    )
    (func (export "trap-same-index")
      (call $new-a)
      (call $stream.forward (global.get $rA) (global.get $rA))
      unreachable
    )
    (func (export "trap-src-reader-copying")
      (local $ret i32)
      (call $new-a)
      (call $new-b)
      (local.set $ret (call $stream.read (global.get $rA) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $stream.forward (global.get $rA) (global.get $wB))
      unreachable
    )
    (func (export "trap-dest-writer-copying")
      (local $ret i32)
      (call $new-a)
      (call $new-b)
      (local.set $ret (call $stream.write (global.get $wB) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $stream.forward (global.get $rA) (global.get $wB))
      unreachable
    )
    (func (export "trap-src-reader-in-set")
      (call $new-a)
      (call $new-b)
      (call $waitable.join (global.get $rA) (call $waitable-set.new))
      (call $stream.forward (global.get $rA) (global.get $wB))
      unreachable
    )
    (func (export "trap-dest-writer-in-set")
      (call $new-a)
      (call $new-b)
      (call $waitable.join (global.get $wB) (call $waitable-set.new))
      (call $stream.forward (global.get $rA) (global.get $wB))
      unreachable
    )
    (func (export "trap-src-reader-done")
      (local $ret i32)
      (call $new-a)
      (call $new-b)
      (call $stream.drop-writable (global.get $wA))
      (local.set $ret (call $stream.read (global.get $rA) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const 0x1 (; DROPPED=1 | (0<<4) ;)) (local.get $ret))
        (then unreachable))
      (call $stream.forward (global.get $rA) (global.get $wB))
      unreachable
    )
    (func (export "trap-dest-writer-done")
      (local $ret i32)
      (call $new-a)
      (call $new-b)
      (call $stream.drop-readable (global.get $rB))
      (local.set $ret (call $stream.write (global.get $wB) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const 0x1 (; DROPPED=1 | (0<<4) ;)) (local.get $ret))
        (then unreachable))
      (call $stream.forward (global.get $rA) (global.get $wB))
      unreachable
    )
    (func (export "trap-use-after-forward")
      (call $new-a)
      (call $new-b)
      (call $stream.forward (global.get $rA) (global.get $wB))
      (call $stream.drop-readable (global.get $rA))
      unreachable
    )
    (func (export "trap-stream-forward-of-future-handles")
      (call $fnew-a)
      (call $fnew-b)
      (call $stream.forward (global.get $rA) (global.get $wB))
      unreachable
    )
    (func (export "trap-future-swapped-args")
      (call $fnew-a)
      (call $fnew-b)
      (call $future.forward (global.get $wA) (global.get $rB))
      unreachable
    )
    (func (export "trap-future-reader-copying")
      (local $ret i32)
      (call $fnew-a)
      (call $fnew-b)
      (local.set $ret (call $future.read (global.get $rA) (i32.const 8)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $future.forward (global.get $rA) (global.get $wB))
      unreachable
    )
  )
  (type $ST (stream u8))
  (type $ST32 (stream u32))
  (type $STE (stream))
  (type $FT (future u8))
  (canon waitable-set.new (core func $waitable-set.new))
  (canon waitable-set.poll (memory (core memory $memory "mem")) (core func $waitable-set.poll))
  (canon waitable.join (core func $waitable.join))
  (canon stream.new $ST (core func $stream.new))
  (canon stream.read $ST async (memory (core memory $memory "mem")) (core func $stream.read))
  (canon stream.write $ST async (memory (core memory $memory "mem")) (core func $stream.write))
  (canon stream.cancel-read $ST (core func $stream.cancel-read))
  (canon stream.cancel-write $ST (core func $stream.cancel-write))
  (canon stream.drop-readable $ST (core func $stream.drop-readable))
  (canon stream.drop-writable $ST (core func $stream.drop-writable))
  (canon stream.forward $ST (core func $stream.forward))
  (canon stream.forward $ST32 (core func $stream.forward-u32))
  (canon stream.new $STE (core func $stream.new-e))
  (canon stream.read $STE async (core func $stream.read-e))
  (canon stream.write $STE async (core func $stream.write-e))
  (canon stream.forward $STE (core func $stream.forward-e))
  (canon future.new $FT (core func $future.new))
  (canon future.read $FT async (memory (core memory $memory "mem")) (core func $future.read))
  (canon future.write $FT async (memory (core memory $memory "mem")) (core func $future.write))
  (canon future.drop-readable $FT (core func $future.drop-readable))
  (canon future.drop-writable $FT (core func $future.drop-writable))
  (canon future.forward $FT (core func $future.forward))
  (core instance $m (instantiate $M (with "" (instance
    (export "mem" (memory $memory "mem"))
    (export "waitable-set.new" (func $waitable-set.new))
    (export "waitable-set.poll" (func $waitable-set.poll))
    (export "waitable.join" (func $waitable.join))
    (export "stream.new" (func $stream.new))
    (export "stream.read" (func $stream.read))
    (export "stream.write" (func $stream.write))
    (export "stream.cancel-read" (func $stream.cancel-read))
    (export "stream.cancel-write" (func $stream.cancel-write))
    (export "stream.drop-readable" (func $stream.drop-readable))
    (export "stream.drop-writable" (func $stream.drop-writable))
    (export "stream.forward" (func $stream.forward))
    (export "stream.forward-u32" (func $stream.forward-u32))
    (export "stream.new-e" (func $stream.new-e))
    (export "stream.read-e" (func $stream.read-e))
    (export "stream.write-e" (func $stream.write-e))
    (export "stream.forward-e" (func $stream.forward-e))
    (export "future.new" (func $future.new))
    (export "future.read" (func $future.read))
    (export "future.write" (func $future.write))
    (export "future.drop-readable" (func $future.drop-readable))
    (export "future.drop-writable" (func $future.drop-writable))
    (export "future.forward" (func $future.forward))
  ))))
  (func (export "forward-then-write-then-read") (result u32) (canon lift (core func $m "forward-then-write-then-read")))
  (func (export "forward-then-read-then-write") (result u32) (canon lift (core func $m "forward-then-read-then-write")))
  (func (export "read-then-forward-then-write") (result u32) (canon lift (core func $m "read-then-forward-then-write")))
  (func (export "rendezvous-during-forward") (result u32) (canon lift (core func $m "rendezvous-during-forward")))
  (func (export "pending-read-in-set-before-forward") (result u32) (canon lift (core func $m "pending-read-in-set-before-forward")))
  (func (export "no-event-from-forward") (result u32) (canon lift (core func $m "no-event-from-forward")))
  (func (export "zero-length-read-carried-over") (result u32) (canon lift (core func $m "zero-length-read-carried-over")))
  (func (export "zero-length-write-then-forward") (result u32) (canon lift (core func $m "zero-length-write-then-forward")))
  (func (export "dest-reader-dropped-before-forward") (result u32) (canon lift (core func $m "dest-reader-dropped-before-forward")))
  (func (export "dest-reader-dropped-before-forward-blocked-writer") (result u32) (canon lift (core func $m "dest-reader-dropped-before-forward-blocked-writer")))
  (func (export "dest-reader-dropped-after-forward") (result u32) (canon lift (core func $m "dest-reader-dropped-after-forward")))
  (func (export "src-writer-dropped-before-forward") (result u32) (canon lift (core func $m "src-writer-dropped-before-forward")))
  (func (export "src-writer-dropped-after-forward") (result u32) (canon lift (core func $m "src-writer-dropped-after-forward")))
  (func (export "cancel-carried-over-read") (result u32) (canon lift (core func $m "cancel-carried-over-read")))
  (func (export "self-forward") (result u32) (canon lift (core func $m "self-forward")))
  (func (export "forward-chain") (result u32) (canon lift (core func $m "forward-chain")))
  (func (export "forward-cycle") (result u32) (canon lift (core func $m "forward-cycle")))
  (func (export "future-forward-then-write-then-read") (result u32) (canon lift (core func $m "future-forward-then-write-then-read")))
  (func (export "future-forward-read-then-write") (result u32) (canon lift (core func $m "future-forward-read-then-write")))
  (func (export "future-rendezvous-during-forward") (result u32) (canon lift (core func $m "future-rendezvous-during-forward")))
  (func (export "future-forward-dest-reader-dropped") (result u32) (canon lift (core func $m "future-forward-dest-reader-dropped")))
  (func (export "future-forward-dest-reader-dropped-blocked-writer") (result u32) (canon lift (core func $m "future-forward-dest-reader-dropped-blocked-writer")))
  (func (export "future-forward-discards-unwritten-writer") (result u32) (canon lift (core func $m "future-forward-discards-unwritten-writer")))
  (func (export "future-self-forward") (result u32) (canon lift (core func $m "future-self-forward")))
  (func (export "future-forward-chain") (result u32) (canon lift (core func $m "future-forward-chain")))
  (func (export "empty-element-type") (result u32) (canon lift (core func $m "empty-element-type")))
  (func (export "trap-swapped-args") (canon lift (core func $m "trap-swapped-args")))
  (func (export "trap-type-mismatch") (canon lift (core func $m "trap-type-mismatch")))
  (func (export "trap-same-index") (canon lift (core func $m "trap-same-index")))
  (func (export "trap-src-reader-copying") (canon lift (core func $m "trap-src-reader-copying")))
  (func (export "trap-dest-writer-copying") (canon lift (core func $m "trap-dest-writer-copying")))
  (func (export "trap-src-reader-in-set") (canon lift (core func $m "trap-src-reader-in-set")))
  (func (export "trap-dest-writer-in-set") (canon lift (core func $m "trap-dest-writer-in-set")))
  (func (export "trap-src-reader-done") (canon lift (core func $m "trap-src-reader-done")))
  (func (export "trap-dest-writer-done") (canon lift (core func $m "trap-dest-writer-done")))
  (func (export "trap-use-after-forward") (canon lift (core func $m "trap-use-after-forward")))
  (func (export "trap-stream-forward-of-future-handles") (canon lift (core func $m "trap-stream-forward-of-future-handles")))
  (func (export "trap-future-swapped-args") (canon lift (core func $m "trap-future-swapped-args")))
  (func (export "trap-future-reader-copying") (canon lift (core func $m "trap-future-reader-copying")))
)

(component instance $i $Tester)
(assert_return (invoke "forward-then-write-then-read") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "forward-then-read-then-write") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "read-then-forward-then-write") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "rendezvous-during-forward") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "pending-read-in-set-before-forward") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "no-event-from-forward") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "zero-length-read-carried-over") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "zero-length-write-then-forward") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "dest-reader-dropped-before-forward") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "dest-reader-dropped-before-forward-blocked-writer") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "dest-reader-dropped-after-forward") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "src-writer-dropped-before-forward") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "src-writer-dropped-after-forward") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "cancel-carried-over-read") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "self-forward") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "forward-chain") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "forward-cycle") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "future-forward-then-write-then-read") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "future-forward-read-then-write") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "future-rendezvous-during-forward") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "future-forward-dest-reader-dropped") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "future-forward-dest-reader-dropped-blocked-writer") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "future-forward-discards-unwritten-writer") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "future-self-forward") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "future-forward-chain") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "empty-element-type") (u32.const 42))
(component instance $i $Tester)
(assert_trap (invoke "trap-swapped-args") "handle index 2 used with the wrong type")
(component instance $i $Tester)
(assert_trap (invoke "trap-type-mismatch") "handle index 1 used with the wrong type")
(component instance $i $Tester)
(assert_trap (invoke "trap-same-index") "unknown handle index 1")
(component instance $i $Tester)
(assert_trap (invoke "trap-src-reader-copying") "cannot forward busy stream")
(component instance $i $Tester)
(assert_trap (invoke "trap-dest-writer-copying") "cannot forward busy stream")
(component instance $i $Tester)
(assert_trap (invoke "trap-src-reader-in-set") "cannot forward stream while it's in a waitable set")
(component instance $i $Tester)
(assert_trap (invoke "trap-dest-writer-in-set") "cannot forward stream while it's in a waitable set")
(component instance $i $Tester)
(assert_trap (invoke "trap-src-reader-done") "cannot forward stream after being notified that the writable end dropped")
(component instance $i $Tester)
(assert_trap (invoke "trap-dest-writer-done") "cannot forward stream after being notified that the readable end dropped")
(component instance $i $Tester)
(assert_trap (invoke "trap-use-after-forward") "unknown handle index 1")
(component instance $i $Tester)
(assert_trap (invoke "trap-stream-forward-of-future-handles") "handle index 1 used with the wrong type")
(component instance $i $Tester)
(assert_trap (invoke "trap-future-swapped-args") "handle index 2 used with the wrong type")
(component instance $i $Tester)
(assert_trap (invoke "trap-future-reader-copying") "cannot forward busy future")

;; A proxying use case: $P produces a stream, $X splices it into a stream of its
;; own and hands the readable end on, and $D consumes it. Because $X gives up
;; both handles in the same call, the copy from $P to $D runs with $X holding no
;; stream ends at all.
(component definition $ProxyTester
  (component $P
    (core module $Memory (memory (export "mem") 1))
    (core instance $memory (instantiate $Memory))
    (core module $PM
      (import "" "mem" (memory 1))
      (import "" "stream.new" (func $stream.new (result i64)))
      (import "" "stream.write" (func $stream.write (param i32 i32 i32) (result i32)))
      (global $w (mut i32) (i32.const 0))
      (func (export "start") (result i32)
        (local $ret64 i64)
        (local.set $ret64 (call $stream.new))
        (global.set $w (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
        (i32.wrap_i64 (local.get $ret64))
      )
      (func (export "write4") (result i32)
        (i32.store (i32.const 0) (i32.const 0x04030201))
        (call $stream.write (global.get $w) (i32.const 0) (i32.const 4))
      )
    )
    (type $ST (stream u8))
    (canon stream.new $ST (core func $stream.new))
    (canon stream.write $ST async (memory (core memory $memory "mem")) (core func $stream.write))
    (core instance $pm (instantiate $PM (with "" (instance
      (export "mem" (memory $memory "mem"))
      (export "stream.new" (func $stream.new))
      (export "stream.write" (func $stream.write))
    ))))
    (func (export "start") (result (stream u8)) (canon lift (core func $pm "start")))
    (func (export "write4") (result u32) (canon lift (core func $pm "write4")))
  )
  (component $X
    (core module $XM
      (import "" "stream.new" (func $stream.new (result i64)))
      (import "" "stream.forward" (func $stream.forward (param i32 i32)))
      (func (export "proxy") (param $in i32) (result i32)
        (local $ret64 i64) (local $r i32) (local $w i32)
        (local.set $ret64 (call $stream.new))
        (local.set $r (i32.wrap_i64 (local.get $ret64)))
        (local.set $w (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
        ;; splice the incoming stream into the outgoing one, giving up both the
        ;; incoming readable end and the outgoing writable end
        (call $stream.forward (local.get $in) (local.get $w))
        (local.get $r)
      )
    )
    (type $ST (stream u8))
    (canon stream.new $ST (core func $stream.new))
    (canon stream.forward $ST (core func $stream.forward))
    (core instance $xm (instantiate $XM (with "" (instance
      (export "stream.new" (func $stream.new))
      (export "stream.forward" (func $stream.forward))
    ))))
    (func (export "proxy") (param "in" (stream u8)) (result (stream u8))
      (canon lift (core func $xm "proxy")))
  )
  (component $D
    (import "p" (instance $p
      (export "start" (func (result (stream u8))))
      (export "write4" (func (result u32)))
    ))
    (import "x" (instance $x
      (export "proxy" (func (param "in" (stream u8)) (result (stream u8))))
    ))
    (core module $Memory (memory (export "mem") 1))
    (core instance $memory (instantiate $Memory))
    (core module $DM
      (import "" "mem" (memory 1))
      (import "" "start" (func $start (result i32)))
      (import "" "write4" (func $write4 (result i32)))
      (import "" "proxy" (func $proxy (param i32) (result i32)))
      (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
      (import "" "waitable-set.poll" (func $waitable-set.poll (param i32 i32) (result i32)))
      (import "" "waitable.join" (func $waitable.join (param i32 i32)))
      (import "" "stream.read" (func $stream.read (param i32 i32 i32) (result i32)))
      (import "" "stream.drop-readable" (func $stream.drop-readable (param i32)))

      (func (export "proxy-read-then-write") (result i32)
        (local $ret i32) (local $rq i32) (local $ws i32)
        (local.set $rq (call $proxy (call $start)))
        (local.set $ret (call $stream.read (local.get $rq) (i32.const 8) (i32.const 4)))
        (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
          (then unreachable))

        ;; $P's write rendezvouses with $D's read even though the stream $D is
        ;; reading from was created by $X
        (local.set $ret (call $write4))
        (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (local.get $ret))
          (then unreachable))
        (if (i32.ne (i32.const 0x04030201) (i32.load (i32.const 8)))
          (then unreachable))

        (local.set $ws (call $waitable-set.new))
        (call $waitable.join (local.get $rq) (local.get $ws))
        (local.set $ret (call $waitable-set.poll (local.get $ws) (i32.const 32)))
        (if (i32.ne (i32.const 2 (; STREAM_READ ;)) (local.get $ret))
          (then unreachable))
        (if (i32.ne (local.get $rq) (i32.load (i32.const 32)))
          (then unreachable))
        (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (i32.load (i32.const 36)))
          (then unreachable))

        (i32.const 42)
      )
      (func (export "proxy-write-then-read") (result i32)
        (local $ret i32) (local $rq i32)
        (local.set $rq (call $proxy (call $start)))
        (local.set $ret (call $write4))
        (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
          (then unreachable))
        (local.set $ret (call $stream.read (local.get $rq) (i32.const 8) (i32.const 4)))
        (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (local.get $ret))
          (then unreachable))
        (if (i32.ne (i32.const 0x04030201) (i32.load (i32.const 8)))
          (then unreachable))
        (i32.const 43)
      )
      (func (export "proxy-drop-reader") (result i32)
        (local $ret i32) (local $rq i32)
        (local.set $rq (call $proxy (call $start)))
        ;; dropping the far end of the spliced stream is visible to $P
        (call $stream.drop-readable (local.get $rq))
        (local.set $ret (call $write4))
        (if (i32.ne (i32.const 0x1 (; DROPPED=1 | (0<<4) ;)) (local.get $ret))
          (then unreachable))
        (i32.const 44)
      )
    )
    (type $ST (stream u8))
    (canon lower (func $p "start") (memory (core memory $memory "mem")) (core func $start))
    (canon lower (func $p "write4") (memory (core memory $memory "mem")) (core func $write4))
    (canon lower (func $x "proxy") (memory (core memory $memory "mem")) (core func $proxy))
    (canon waitable-set.new (core func $waitable-set.new))
    (canon waitable-set.poll (memory (core memory $memory "mem")) (core func $waitable-set.poll))
    (canon waitable.join (core func $waitable.join))
    (canon stream.read $ST async (memory (core memory $memory "mem")) (core func $stream.read))
    (canon stream.drop-readable $ST (core func $stream.drop-readable))
    (core instance $dm (instantiate $DM (with "" (instance
      (export "mem" (memory $memory "mem"))
      (export "start" (func $start))
      (export "write4" (func $write4))
      (export "proxy" (func $proxy))
      (export "waitable-set.new" (func $waitable-set.new))
      (export "waitable-set.poll" (func $waitable-set.poll))
      (export "waitable.join" (func $waitable.join))
      (export "stream.read" (func $stream.read))
      (export "stream.drop-readable" (func $stream.drop-readable))
    ))))
    (func (export "proxy-read-then-write") (result u32) (canon lift (core func $dm "proxy-read-then-write")))
    (func (export "proxy-write-then-read") (result u32) (canon lift (core func $dm "proxy-write-then-read")))
    (func (export "proxy-drop-reader") (result u32) (canon lift (core func $dm "proxy-drop-reader")))
  )
  (instance $p (instantiate $P))
  (instance $x (instantiate $X))
  (instance $d (instantiate $D (with "p" (instance $p)) (with "x" (instance $x))))
  (func (export "proxy-read-then-write") (alias export $d "proxy-read-then-write"))
  (func (export "proxy-write-then-read") (alias export $d "proxy-write-then-read"))
  (func (export "proxy-drop-reader") (alias export $d "proxy-drop-reader"))
)

(component instance $i $ProxyTester)
(assert_return (invoke "proxy-read-then-write") (u32.const 42))
(component instance $i $ProxyTester)
(assert_return (invoke "proxy-write-then-read") (u32.const 43))
(component instance $i $ProxyTester)
(assert_return (invoke "proxy-drop-reader") (u32.const 44))


;; One stream forwarded five times, ping-ponging between two components: $C and
;; $D take turns splicing the chain into a stream of their own, and after every
;; splice the surviving writer writes and the surviving reader reads a distinct
;; 4-byte pattern all the way through.
(component definition $PingPongTester
  (component $C
    (core module $Memory (memory (export "mem") 1))
    (core instance $memory (instantiate $Memory))
    (core module $CM
      (import "" "mem" (memory 1))
      (import "" "stream.new" (func $stream.new (result i64)))
      (import "" "stream.read" (func $stream.read (param i32 i32 i32) (result i32)))
      (import "" "stream.write" (func $stream.write (param i32 i32 i32) (result i32)))
      (import "" "stream.forward" (func $stream.forward (param i32 i32)))
      (import "" "stream.drop-writable" (func $stream.drop-writable (param i32)))

      (global $r (mut i32) (i32.const 0))  ;; the chain's readable end, while $C holds it
      (global $w (mut i32) (i32.const 0))  ;; the writable end of the stream made by "fresh"

      ;; splice the incoming readable end into a fresh local stream, keeping the
      ;; local readable end: $C becomes the reader of the merged stream
      (func (export "splice") (param $in i32)
        (local $ret64 i64)
        (local.set $ret64 (call $stream.new))
        (global.set $r (i32.wrap_i64 (local.get $ret64)))
        (call $stream.forward (local.get $in)
          (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
      )
      (func (export "read4") (param $expected i32) (result i32)
        (local $ret i32)
        (local.set $ret (call $stream.read (global.get $r) (i32.const 8) (i32.const 4)))
        (if (i32.eq (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (local.get $ret))
          (then
            (if (i32.ne (i32.load (i32.const 8)) (local.get $expected))
              (then unreachable))))
        (local.get $ret)
      )
      ;; give the chain's readable end back to $D so that it can take the next turn
      (func (export "hand-back") (result i32)
        (global.get $r)
      )
      ;; a brand new stream whose readable end $D can splice in front of the chain
      (func (export "fresh") (result i32)
        (local $ret64 i64)
        (local.set $ret64 (call $stream.new))
        (global.set $w (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
        (i32.wrap_i64 (local.get $ret64))
      )
      (func (export "write4") (param $val i32) (result i32)
        (i32.store (i32.const 0) (local.get $val))
        (call $stream.write (global.get $w) (i32.const 0) (i32.const 4))
      )
      (func (export "drop-writer")
        (call $stream.drop-writable (global.get $w))
      )
    )
    (type $ST (stream u8))
    (canon stream.new $ST (core func $stream.new))
    (canon stream.read $ST async (memory (core memory $memory "mem")) (core func $stream.read))
    (canon stream.write $ST async (memory (core memory $memory "mem")) (core func $stream.write))
    (canon stream.forward $ST (core func $stream.forward))
    (canon stream.drop-writable $ST (core func $stream.drop-writable))
    (core instance $cm (instantiate $CM (with "" (instance
      (export "mem" (memory $memory "mem"))
      (export "stream.new" (func $stream.new))
      (export "stream.read" (func $stream.read))
      (export "stream.write" (func $stream.write))
      (export "stream.forward" (func $stream.forward))
      (export "stream.drop-writable" (func $stream.drop-writable))
    ))))
    (func (export "splice") (param "in" (stream u8)) (canon lift (core func $cm "splice")))
    (func (export "read4") (param "expected" u32) (result s32) (canon lift (core func $cm "read4")))
    (func (export "hand-back") (result (stream u8)) (canon lift (core func $cm "hand-back")))
    (func (export "fresh") (result (stream u8)) (canon lift (core func $cm "fresh")))
    (func (export "write4") (param "val" u32) (result s32) (canon lift (core func $cm "write4")))
    (func (export "drop-writer") (canon lift (core func $cm "drop-writer")))
  )
  (component $D
    (import "c" (instance $c
      (export "splice" (func (param "in" (stream u8))))
      (export "read4" (func (param "expected" u32) (result s32)))
      (export "hand-back" (func (result (stream u8))))
      (export "fresh" (func (result (stream u8))))
      (export "write4" (func (param "val" u32) (result s32)))
      (export "drop-writer" (func))
    ))
    (core module $Memory (memory (export "mem") 1))
    (core instance $memory (instantiate $Memory))
    (core module $DM
      (import "" "mem" (memory 1))
      (import "" "c-splice" (func $c-splice (param i32)))
      (import "" "c-read4" (func $c-read4 (param i32) (result i32)))
      (import "" "c-hand-back" (func $c-hand-back (result i32)))
      (import "" "c-fresh" (func $c-fresh (result i32)))
      (import "" "c-write4" (func $c-write4 (param i32) (result i32)))
      (import "" "c-drop-writer" (func $c-drop-writer))
      (import "" "stream.new" (func $stream.new (result i64)))
      (import "" "stream.read" (func $stream.read (param i32 i32 i32) (result i32)))
      (import "" "stream.write" (func $stream.write (param i32 i32 i32) (result i32)))
      (import "" "stream.forward" (func $stream.forward (param i32 i32)))
      (import "" "stream.drop-readable" (func $stream.drop-readable (param i32)))
      (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
      (import "" "waitable-set.poll" (func $waitable-set.poll (param i32 i32) (result i32)))
      (import "" "waitable-set.drop" (func $waitable-set.drop (param i32)))
      (import "" "waitable.join" (func $waitable.join (param i32 i32)))

      (global $r (mut i32) (i32.const 0))  ;; the chain's readable end, while $D holds it
      (global $w (mut i32) (i32.const 0))  ;; the chain's writable end, while $D holds it

      ;; the mirror image of $C's "splice": $D becomes the reader
      (func $d-splice (param $in i32)
        (local $ret64 i64)
        (local.set $ret64 (call $stream.new))
        (global.set $r (i32.wrap_i64 (local.get $ret64)))
        (call $stream.forward (local.get $in)
          (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
      )
      (func $d-write4 (param $val i32)
        (local $ret i32)
        (i32.store (i32.const 0) (local.get $val))
        (local.set $ret (call $stream.write (global.get $w) (i32.const 0) (i32.const 4)))
        (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
          (then unreachable))
      )
      (func $d-read4 (param $expected i32)
        (local $ret i32)
        (local.set $ret (call $stream.read (global.get $r) (i32.const 8) (i32.const 4)))
        (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;)) (local.get $ret))
          (then unreachable))
        (if (i32.ne (i32.load (i32.const 8)) (local.get $expected))
          (then unreachable))
      )
      (func $expect-c-read4 (param $expected i32)
        (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;))
                    (call $c-read4 (local.get $expected)))
          (then unreachable))
      )
      ;; the blocked write is completed by the far side's read, so its event has
      ;; to be taken before the same writable end can be used for the next hop
      (func $poll (param $waitable i32) (param $event i32) (param $payload i32)
        (local $ws i32)
        (local.set $ws (call $waitable-set.new))
        (call $waitable.join (local.get $waitable) (local.get $ws))
        (if (i32.ne (local.get $event) (call $waitable-set.poll (local.get $ws) (i32.const 32)))
          (then unreachable))
        (if (i32.ne (local.get $waitable) (i32.load (i32.const 32)))
          (then unreachable))
        (if (i32.ne (local.get $payload) (i32.load (i32.const 36)))
          (then unreachable))
        (call $waitable.join (local.get $waitable) (i32.const 0))
        (call $waitable-set.drop (local.get $ws))
      )

      (func (export "run") (result i32)
        (local $ret i32) (local $ret64 i64)

        ;; $D makes the stream and keeps the writable end for the first four hops
        (local.set $ret64 (call $stream.new))
        (global.set $r (i32.wrap_i64 (local.get $ret64)))
        (global.set $w (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))

        ;; hop 1: $C splices, so the merged stream runs from $D's writer to $C's
        ;; reader and the copy crosses a component boundary
        (call $c-splice (global.get $r))
        (call $d-write4 (i32.const 0x11111111))
        (call $expect-c-read4 (i32.const 0x11111111))
        (call $poll (global.get $w) (i32.const 3 (; STREAM_WRITE ;)) (i32.const 0x40))

        ;; hop 2: $C hands the reader back and $D splices, so this time both ends
        ;; of the merged stream are $D's own
        (call $d-splice (call $c-hand-back))
        (call $d-write4 (i32.const 0x22222222))
        (call $d-read4 (i32.const 0x22222222))
        (call $poll (global.get $w) (i32.const 3 (; STREAM_WRITE ;)) (i32.const 0x40))

        ;; hop 3: and back over to $C
        (call $c-splice (global.get $r))
        (call $d-write4 (i32.const 0x33333333))
        (call $expect-c-read4 (i32.const 0x33333333))
        (call $poll (global.get $w) (i32.const 3 (; STREAM_WRITE ;)) (i32.const 0x40))

        ;; hop 4: and back to $D
        (call $d-splice (call $c-hand-back))
        (call $d-write4 (i32.const 0x44444444))
        (call $d-read4 (i32.const 0x44444444))
        (call $poll (global.get $w) (i32.const 3 (; STREAM_WRITE ;)) (i32.const 0x40))

        ;; hop 5: $D splices a stream made by $C in front of the chain, which is
        ;; the one way the writer can end up in the other component. $D keeps the
        ;; reader it already had, so the copy now runs $C -> $D.
        (call $stream.forward (call $c-fresh) (global.get $w))
        (local.set $ret (call $stream.read (global.get $r) (i32.const 8) (i32.const 4)))
        (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
          (then unreachable))
        (if (i32.ne (i32.const 0x40 (; COMPLETED=0 | (4<<4) ;))
                    (call $c-write4 (i32.const 0x55555555)))
          (then unreachable))
        (call $poll (global.get $r) (i32.const 2 (; STREAM_READ ;)) (i32.const 0x40))
        (if (i32.ne (i32.load (i32.const 8)) (i32.const 0x55555555))
          (then unreachable))

        (call $stream.drop-readable (global.get $r))
        (call $c-drop-writer)
        (i32.const 42)
      )
    )
    (type $ST (stream u8))
    (canon lower (func $c "splice") (memory (core memory $memory "mem")) (core func $c-splice))
    (canon lower (func $c "read4") (memory (core memory $memory "mem")) (core func $c-read4))
    (canon lower (func $c "hand-back") (memory (core memory $memory "mem")) (core func $c-hand-back))
    (canon lower (func $c "fresh") (memory (core memory $memory "mem")) (core func $c-fresh))
    (canon lower (func $c "write4") (memory (core memory $memory "mem")) (core func $c-write4))
    (canon lower (func $c "drop-writer") (core func $c-drop-writer))
    (canon stream.new $ST (core func $stream.new))
    (canon stream.read $ST async (memory (core memory $memory "mem")) (core func $stream.read))
    (canon stream.write $ST async (memory (core memory $memory "mem")) (core func $stream.write))
    (canon stream.forward $ST (core func $stream.forward))
    (canon stream.drop-readable $ST (core func $stream.drop-readable))
    (canon waitable-set.new (core func $waitable-set.new))
    (canon waitable-set.poll (memory (core memory $memory "mem")) (core func $waitable-set.poll))
    (canon waitable-set.drop (core func $waitable-set.drop))
    (canon waitable.join (core func $waitable.join))
    (core instance $dm (instantiate $DM (with "" (instance
      (export "mem" (memory $memory "mem"))
      (export "c-splice" (func $c-splice))
      (export "c-read4" (func $c-read4))
      (export "c-hand-back" (func $c-hand-back))
      (export "c-fresh" (func $c-fresh))
      (export "c-write4" (func $c-write4))
      (export "c-drop-writer" (func $c-drop-writer))
      (export "stream.new" (func $stream.new))
      (export "stream.read" (func $stream.read))
      (export "stream.write" (func $stream.write))
      (export "stream.forward" (func $stream.forward))
      (export "stream.drop-readable" (func $stream.drop-readable))
      (export "waitable-set.new" (func $waitable-set.new))
      (export "waitable-set.poll" (func $waitable-set.poll))
      (export "waitable-set.drop" (func $waitable-set.drop))
      (export "waitable.join" (func $waitable.join))
    ))))
    (func (export "run") (result u32) (canon lift (core func $dm "run")))
  )
  (instance $c (instantiate $C))
  (instance $d (instantiate $D (with "c" (instance $c))))
  (func (export "run") (alias export $d "run"))
)

(component instance $i $PingPongTester)
(assert_return (invoke "run") (u32.const 42))


(assert_invalid
  (component
    (type $FT (future u8))
    (canon stream.forward $FT (core func $f))
  )
  "`stream.forward` requires a stream type")
(assert_invalid
  (component
    (type $ST (stream u8))
    (canon future.forward $ST (core func $f))
  )
  "`future.forward` requires a future type")
