;; Test that DROPPED doesn't override COMPLETED for futures.
(component definition $Tester
  (core module $Memory (memory (export "mem") 1))
  (core instance $memory (instantiate $Memory))
  (core module $M
    (import "" "mem" (memory 1))
    (import "" "waitable.join" (func $waitable.join (param i32 i32)))
    (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
    (import "" "waitable-set.poll" (func $waitable-set.poll (param i32 i32) (result i32)))
    (import "" "future.new" (func $future.new (result i64)))
    (import "" "future.read" (func $future.read (param i32 i32) (result i32)))
    (import "" "future.write" (func $future.write (param i32 i32) (result i32)))
    (import "" "future.drop-readable" (func $future.drop-readable (param i32)))
    (import "" "future.drop-writable" (func $future.drop-writable (param i32)))

    ;; The event returned by waitable-set.poll is stored at [0,8): the waitable
    ;; index at 0 and the payload at 4. The source byte lives at 64, the
    ;; destination byte at 128.
    (global $ws (mut i32) (i32.const 0))
    (global $rx (mut i32) (i32.const 0))
    (global $tx (mut i32) (i32.const 0))

    (func $start
      (global.set $ws (call $waitable-set.new))
      (i32.store8 (i32.const 64) (i32.const 1))
    )
    (start $start)

    (func $expect-event (param $code i32) (param $index i32) (param $payload i32)
      (if (i32.ne (call $waitable-set.poll (global.get $ws) (i32.const 0)) (local.get $code))
        (then unreachable))
      (if (i32.ne (i32.load (i32.const 0)) (local.get $index))
        (then unreachable))
      (if (i32.ne (i32.load (i32.const 4)) (local.get $payload))
        (then unreachable))
    )
    (func $expect-no-event
      (if (i32.ne (call $waitable-set.poll (global.get $ws) (i32.const 0))
                  (i32.const 0 (; NONE ;)))
        (then unreachable))
    )
    (func $new-future
      (local $ret64 i64)
      (local.set $ret64 (call $future.new))
      (global.set $rx (i32.wrap_i64 (local.get $ret64)))
      (global.set $tx (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
    )

    ;; The reader blocks first, so future.write consumes the writer's own
    ;; completion inline. The writable end is then done and may be dropped
    ;; before the reader has observed anything.
    (func (export "writer-completes-inline") (result i32)
      (call $new-future)
      (call $waitable.join (global.get $rx) (global.get $ws))
      (if (i32.ne (call $future.read (global.get $rx) (i32.const 128))
                  (i32.const -1 (; BLOCKED ;)))
        (then unreachable))
      (if (i32.ne (call $future.write (global.get $tx) (i32.const 64))
                  (i32.const 0 (; COMPLETED ;)))
        (then unreachable))
      (call $future.drop-writable (global.get $tx))
      ;; COMPLETED, not DROPPED: the copy happened before the drop
      (call $expect-event (i32.const 4 (; FUTURE_READ ;)) (global.get $rx)
                          (i32.const 0 (; COMPLETED ;)))
      (call $expect-no-event)
      (if (i32.ne (i32.load8_u (i32.const 128)) (i32.const 1))
        (then unreachable))
      (i32.const 42)
    )

    ;; The mirror: the writer blocks first, so future.read consumes the
    ;; reader's completion inline and the blocked writer polls for its own.
    (func (export "reader-completes-inline") (result i32)
      (call $new-future)
      (call $waitable.join (global.get $tx) (global.get $ws))
      (if (i32.ne (call $future.write (global.get $tx) (i32.const 64))
                  (i32.const -1 (; BLOCKED ;)))
        (then unreachable))
      (if (i32.ne (call $future.read (global.get $rx) (i32.const 128))
                  (i32.const 0 (; COMPLETED ;)))
        (then unreachable))
      (call $future.drop-readable (global.get $rx))
      (call $expect-event (i32.const 5 (; FUTURE_WRITE ;)) (global.get $tx)
                          (i32.const 0 (; COMPLETED ;)))
      (call $expect-no-event)
      (call $waitable.join (global.get $tx) (i32.const 0))
      (call $future.drop-writable (global.get $tx))
      (if (i32.ne (i32.load8_u (i32.const 128)) (i32.const 1))
        (then unreachable))
      (i32.const 42)
    )
  )
  (type $FT (future u8))
  (canon waitable.join (core func $waitable.join))
  (canon waitable-set.new (core func $waitable-set.new))
  (canon waitable-set.poll (memory (core memory $memory "mem")) (core func $waitable-set.poll))
  (canon future.new $FT (core func $future.new))
  (canon future.read $FT async (memory (core memory $memory "mem")) (core func $future.read))
  (canon future.write $FT async (memory (core memory $memory "mem")) (core func $future.write))
  (canon future.drop-readable $FT (core func $future.drop-readable))
  (canon future.drop-writable $FT (core func $future.drop-writable))
  (core instance $m (instantiate $M (with "" (instance
    (export "mem" (memory $memory "mem"))
    (export "waitable.join" (func $waitable.join))
    (export "waitable-set.new" (func $waitable-set.new))
    (export "waitable-set.poll" (func $waitable-set.poll))
    (export "future.new" (func $future.new))
    (export "future.read" (func $future.read))
    (export "future.write" (func $future.write))
    (export "future.drop-readable" (func $future.drop-readable))
    (export "future.drop-writable" (func $future.drop-writable))
  ))))
  (func (export "writer-completes-inline") (result u32) (canon lift (core func $m "writer-completes-inline")))
  (func (export "reader-completes-inline") (result u32) (canon lift (core func $m "reader-completes-inline")))
)
(component instance $i $Tester)
(assert_return (invoke "writer-completes-inline") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "reader-completes-inline") (u32.const 42))
