;; Tests the trap conditions associated with mixing synchronous and
;; asynchronous waiting on the same waitable.
(component definition $Tester
  (component $C
    (core module $CM
      (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
      (func (export "blocks-forever") (result i32)
        (i32.or (i32.const 2 (; WAIT ;)) (i32.shl (call $waitable-set.new) (i32.const 4)))
      )
      (func (export "blocks-forever-cb") (param i32 i32 i32) (result i32)
        unreachable
      )
    )
    (canon waitable-set.new (core func $waitable-set.new))
    (core instance $cm (instantiate $CM (with "" (instance
      (export "waitable-set.new" (func $waitable-set.new))
    ))))
    (func (export "blocks-forever") async (result u32) (canon lift
      (core func $cm "blocks-forever")
      async (callback (func $cm "blocks-forever-cb"))
    ))
  )
  (instance $c (instantiate $C))
  (component $Main
    (import "c" (instance $c
      (export "blocks-forever" (func async (result u32)))
    ))
    (core module $MemTable
      (table (export "ftbl") 4 funcref)
      (memory (export "mem") 1)
    )
    (core instance $memTable (instantiate $MemTable))

    (core module $m
      (import "" "thread.new-indirect" (func $thread.new-indirect (param i32 i32) (result i32)))
      (import "" "thread.yield-then-resume" (func $thread.yield-then-resume (param i32) (result i32)))
      (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
      (import "" "waitable.join" (func $waitable.join (param i32 i32)))
      (import "" "subtask.cancel-sync" (func $subtask.cancel-sync (param i32) (result i32)))
      (import "" "future.new" (func $future.new (result i64)))
      (import "" "future.read-sync" (func $future.read-sync (param i32 i32) (result i32)))
      (import "" "future.write-sync" (func $future.write-sync (param i32 i32) (result i32)))
      (import "" "future.read-async" (func $future.read-async (param i32 i32) (result i32)))
      (import "" "future.write-async" (func $future.write-async (param i32 i32) (result i32)))
      (import "" "future.cancel-read-sync" (func $future.cancel-read-sync (param i32) (result i32)))
      (import "" "future.cancel-write-sync" (func $future.cancel-write-sync (param i32) (result i32)))
      (import "" "stream.new" (func $stream.new (result i64)))
      (import "" "stream.read-sync" (func $stream.read-sync (param i32 i32 i32) (result i32)))
      (import "" "stream.write-sync" (func $stream.write-sync (param i32 i32 i32) (result i32)))
      (import "" "stream.read-async" (func $stream.read-async (param i32 i32 i32) (result i32)))
      (import "" "stream.write-async" (func $stream.write-async (param i32 i32 i32) (result i32)))
      (import "" "stream.cancel-read-sync" (func $stream.cancel-read-sync (param i32) (result i32)))
      (import "" "stream.cancel-write-sync" (func $stream.cancel-write-sync (param i32) (result i32)))
      (import "" "blocks-forever" (func $blocks-forever (param i32) (result i32)))
      (import "" "ftbl" (table $ftbl 4 funcref))

      (func $new-future-rx (result i32)
        (i32.wrap_i64 (call $future.new))
      )
      (func $new-future-tx (result i32)
        (i32.wrap_i64 (i64.shr_u (call $future.new) (i64.const 32)))
      )
      (func $new-stream-rx (result i32)
        (i32.wrap_i64 (call $stream.new))
      )
      (func $new-stream-tx (result i32)
        (i32.wrap_i64 (i64.shr_u (call $stream.new) (i64.const 32)))
      )
      (func $spawn-and-yield (param $idx i32) (param $arg i32)
        (drop (call $thread.yield-then-resume
                (call $thread.new-indirect (local.get $idx) (local.get $arg))))
      )
      (func $assert-blocked (param $ret i32)
        (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
          (then unreachable))
      )

      ;; thread-start funcs used by the join-during-sync-* tests:
      (func $thread-future-read-sync (param $rx i32)
        (drop (call $future.read-sync (local.get $rx) (i32.const 0)))
      )
      (elem (table $ftbl) (i32.const 0) func $thread-future-read-sync)
      (func $thread-future-write-sync (param $tx i32)
        (drop (call $future.write-sync (local.get $tx) (i32.const 0)))
      )
      (elem (table $ftbl) (i32.const 1) func $thread-future-write-sync)
      (func $thread-stream-read-sync (param $rx i32)
        (drop (call $stream.read-sync (local.get $rx) (i32.const 0) (i32.const 4)))
      )
      (elem (table $ftbl) (i32.const 2) func $thread-stream-read-sync)
      (func $thread-stream-write-sync (param $tx i32)
        (drop (call $stream.write-sync (local.get $tx) (i32.const 0) (i32.const 4)))
      )
      (elem (table $ftbl) (i32.const 3) func $thread-stream-write-sync)

      (func (export "join-during-sync-future-read")
        (local $rx i32)
        (local.set $rx (call $new-future-rx))
        (call $spawn-and-yield (i32.const 0) (local.get $rx))
        (call $waitable.join (local.get $rx) (call $waitable-set.new))
        unreachable
      )
      (func (export "join-during-sync-future-write")
        (local $tx i32)
        (local.set $tx (call $new-future-tx))
        (call $spawn-and-yield (i32.const 1) (local.get $tx))
        (call $waitable.join (local.get $tx) (call $waitable-set.new))
        unreachable
      )
      (func (export "join-during-sync-stream-read")
        (local $rx i32)
        (local.set $rx (call $new-stream-rx))
        (call $spawn-and-yield (i32.const 2) (local.get $rx))
        (call $waitable.join (local.get $rx) (call $waitable-set.new))
        unreachable
      )
      (func (export "join-during-sync-stream-write")
        (local $tx i32)
        (local.set $tx (call $new-stream-tx))
        (call $spawn-and-yield (i32.const 3) (local.get $tx))
        (call $waitable.join (local.get $tx) (call $waitable-set.new))
        unreachable
      )

      (func (export "sync-future-read-when-in-set")
        (local $rx i32)
        (local.set $rx (call $new-future-rx))
        (call $waitable.join (local.get $rx) (call $waitable-set.new))
        (drop (call $future.read-sync (local.get $rx) (i32.const 0)))
        unreachable
      )
      (func (export "sync-future-write-when-in-set")
        (local $tx i32)
        (local.set $tx (call $new-future-tx))
        (call $waitable.join (local.get $tx) (call $waitable-set.new))
        (drop (call $future.write-sync (local.get $tx) (i32.const 0)))
        unreachable
      )
      (func (export "sync-stream-read-when-in-set")
        (local $rx i32)
        (local.set $rx (call $new-stream-rx))
        (call $waitable.join (local.get $rx) (call $waitable-set.new))
        (drop (call $stream.read-sync (local.get $rx) (i32.const 0) (i32.const 4)))
        unreachable
      )
      (func (export "sync-stream-write-when-in-set")
        (local $tx i32)
        (local.set $tx (call $new-stream-tx))
        (call $waitable.join (local.get $tx) (call $waitable-set.new))
        (drop (call $stream.write-sync (local.get $tx) (i32.const 0) (i32.const 4)))
        unreachable
      )
      (func (export "sync-future-cancel-read-when-in-set")
        (local $rx i32)
        (local.set $rx (call $new-future-rx))
        (call $assert-blocked (call $future.read-async (local.get $rx) (i32.const 0)))
        (call $waitable.join (local.get $rx) (call $waitable-set.new))
        (drop (call $future.cancel-read-sync (local.get $rx)))
        unreachable
      )

      (func (export "sync-future-cancel-write-when-in-set")
        (local $tx i32)
        (local.set $tx (call $new-future-tx))
        (call $assert-blocked (call $future.write-async (local.get $tx) (i32.const 0)))
        (call $waitable.join (local.get $tx) (call $waitable-set.new))
        (drop (call $future.cancel-write-sync (local.get $tx)))
        unreachable
      )
      (func (export "sync-stream-cancel-read-when-in-set")
        (local $rx i32)
        (local.set $rx (call $new-stream-rx))
        (call $assert-blocked (call $stream.read-async (local.get $rx) (i32.const 0) (i32.const 4)))
        (call $waitable.join (local.get $rx) (call $waitable-set.new))
        (drop (call $stream.cancel-read-sync (local.get $rx)))
        unreachable
      )
      (func (export "sync-stream-cancel-write-when-in-set")
        (local $tx i32)
        (local.set $tx (call $new-stream-tx))
        (call $assert-blocked (call $stream.write-async (local.get $tx) (i32.const 0) (i32.const 4)))
        (call $waitable.join (local.get $tx) (call $waitable-set.new))
        (drop (call $stream.cancel-write-sync (local.get $tx)))
        unreachable
      )

      (func (export "sync-subtask-cancel-when-in-set")
        (local $ret i32) (local $sub i32)
        (local.set $ret (call $blocks-forever (i32.const 0)))
        (if (i32.ne (i32.const 1 (; STARTED ;)) (i32.and (local.get $ret) (i32.const 0xf)))
          (then unreachable))
        (local.set $sub (i32.shr_u (local.get $ret) (i32.const 4)))
        (call $waitable.join (local.get $sub) (call $waitable-set.new))
        (drop (call $subtask.cancel-sync (local.get $sub)))
        unreachable
      )
    )

    (core type $start-func-ty (func (param i32)))
    (alias core export $memTable "ftbl" (core table $ftbl))

    (core func $thread.new-indirect (canon thread.new-indirect $start-func-ty (table $ftbl)))
    (core func $thread.yield-then-resume (canon thread.yield-then-resume))
    (core func $waitable-set.new (canon waitable-set.new))
    (core func $waitable.join (canon waitable.join))
    (core func $subtask.cancel-sync (canon subtask.cancel))
    (type $future (future))
    (type $stream (stream u8))
    (core func $future.new (canon future.new $future))
    (core func $future.read-sync (canon future.read $future (memory $memTable "mem")))
    (core func $future.write-sync (canon future.write $future (memory $memTable "mem")))
    (core func $future.read-async (canon future.read $future async (memory $memTable "mem")))
    (core func $future.write-async (canon future.write $future async (memory $memTable "mem")))
    (core func $future.cancel-read-sync (canon future.cancel-read $future))
    (core func $future.cancel-write-sync (canon future.cancel-write $future))
    (core func $stream.new (canon stream.new $stream))
    (core func $stream.read-sync (canon stream.read $stream (memory $memTable "mem")))
    (core func $stream.write-sync (canon stream.write $stream (memory $memTable "mem")))
    (core func $stream.read-async (canon stream.read $stream async (memory $memTable "mem")))
    (core func $stream.write-async (canon stream.write $stream async (memory $memTable "mem")))
    (core func $stream.cancel-read-sync (canon stream.cancel-read $stream))
    (core func $stream.cancel-write-sync (canon stream.cancel-write $stream))
    (canon lower (func $c "blocks-forever") async (memory $memTable "mem") (core func $blocks-forever))

    (core instance $m (instantiate $m
      (with "" (instance
        (export "thread.new-indirect" (func $thread.new-indirect))
        (export "thread.yield-then-resume" (func $thread.yield-then-resume))
        (export "waitable-set.new" (func $waitable-set.new))
        (export "waitable.join" (func $waitable.join))
        (export "subtask.cancel-sync" (func $subtask.cancel-sync))
        (export "future.new" (func $future.new))
        (export "future.read-sync" (func $future.read-sync))
        (export "future.write-sync" (func $future.write-sync))
        (export "future.read-async" (func $future.read-async))
        (export "future.write-async" (func $future.write-async))
        (export "future.cancel-read-sync" (func $future.cancel-read-sync))
        (export "future.cancel-write-sync" (func $future.cancel-write-sync))
        (export "stream.new" (func $stream.new))
        (export "stream.read-sync" (func $stream.read-sync))
        (export "stream.write-sync" (func $stream.write-sync))
        (export "stream.read-async" (func $stream.read-async))
        (export "stream.write-async" (func $stream.write-async))
        (export "stream.cancel-read-sync" (func $stream.cancel-read-sync))
        (export "stream.cancel-write-sync" (func $stream.cancel-write-sync))
        (export "blocks-forever" (func $blocks-forever))
        (export "ftbl" (table $ftbl))
      ))
    ))
    (func (export "join-during-sync-future-read") async (canon lift (core func $m "join-during-sync-future-read")))
    (func (export "join-during-sync-future-write") async (canon lift (core func $m "join-during-sync-future-write")))
    (func (export "join-during-sync-stream-read") async (canon lift (core func $m "join-during-sync-stream-read")))
    (func (export "join-during-sync-stream-write") async (canon lift (core func $m "join-during-sync-stream-write")))
    (func (export "sync-future-read-when-in-set") async (canon lift (core func $m "sync-future-read-when-in-set")))
    (func (export "sync-future-write-when-in-set") async (canon lift (core func $m "sync-future-write-when-in-set")))
    (func (export "sync-stream-read-when-in-set") async (canon lift (core func $m "sync-stream-read-when-in-set")))
    (func (export "sync-stream-write-when-in-set") async (canon lift (core func $m "sync-stream-write-when-in-set")))
    (func (export "sync-future-cancel-read-when-in-set") async (canon lift (core func $m "sync-future-cancel-read-when-in-set")))
    (func (export "sync-future-cancel-write-when-in-set") async (canon lift (core func $m "sync-future-cancel-write-when-in-set")))
    (func (export "sync-stream-cancel-read-when-in-set") async (canon lift (core func $m "sync-stream-cancel-read-when-in-set")))
    (func (export "sync-stream-cancel-write-when-in-set") async (canon lift (core func $m "sync-stream-cancel-write-when-in-set")))
    (func (export "sync-subtask-cancel-when-in-set") async (canon lift (core func $m "sync-subtask-cancel-when-in-set")))
  )
  (instance $main (instantiate $Main (with "c" (instance $c))))
  (func (export "join-during-sync-future-read") (alias export $main "join-during-sync-future-read"))
  (func (export "join-during-sync-future-write") (alias export $main "join-during-sync-future-write"))
  (func (export "join-during-sync-stream-read") (alias export $main "join-during-sync-stream-read"))
  (func (export "join-during-sync-stream-write") (alias export $main "join-during-sync-stream-write"))
  (func (export "sync-future-read-when-in-set") (alias export $main "sync-future-read-when-in-set"))
  (func (export "sync-future-write-when-in-set") (alias export $main "sync-future-write-when-in-set"))
  (func (export "sync-stream-read-when-in-set") (alias export $main "sync-stream-read-when-in-set"))
  (func (export "sync-stream-write-when-in-set") (alias export $main "sync-stream-write-when-in-set"))
  (func (export "sync-future-cancel-read-when-in-set") (alias export $main "sync-future-cancel-read-when-in-set"))
  (func (export "sync-future-cancel-write-when-in-set") (alias export $main "sync-future-cancel-write-when-in-set"))
  (func (export "sync-stream-cancel-read-when-in-set") (alias export $main "sync-stream-cancel-read-when-in-set"))
  (func (export "sync-stream-cancel-write-when-in-set") (alias export $main "sync-stream-cancel-write-when-in-set"))
  (func (export "sync-subtask-cancel-when-in-set") (alias export $main "sync-subtask-cancel-when-in-set"))
)

(component instance $i $Tester)
(assert_trap (invoke "join-during-sync-future-read") "waitable cannot be used synchronously while added to a waitable set")
(component instance $i $Tester)
(assert_trap (invoke "join-during-sync-future-write") "waitable cannot be used synchronously while added to a waitable set")
(component instance $i $Tester)
(assert_trap (invoke "join-during-sync-stream-read") "waitable cannot be used synchronously while added to a waitable set")
(component instance $i $Tester)
(assert_trap (invoke "join-during-sync-stream-write") "waitable cannot be used synchronously while added to a waitable set")
(component instance $i $Tester)
(assert_trap (invoke "sync-future-read-when-in-set") "waitable cannot be used synchronously while added to a waitable set")
(component instance $i $Tester)
(assert_trap (invoke "sync-future-write-when-in-set") "waitable cannot be used synchronously while added to a waitable set")
(component instance $i $Tester)
(assert_trap (invoke "sync-stream-read-when-in-set") "waitable cannot be used synchronously while added to a waitable set")
(component instance $i $Tester)
(assert_trap (invoke "sync-stream-write-when-in-set") "waitable cannot be used synchronously while added to a waitable set")
(component instance $i $Tester)
(assert_trap (invoke "sync-future-cancel-read-when-in-set") "waitable cannot be used synchronously while added to a waitable set")
(component instance $i $Tester)
(assert_trap (invoke "sync-future-cancel-write-when-in-set") "waitable cannot be used synchronously while added to a waitable set")
(component instance $i $Tester)
(assert_trap (invoke "sync-stream-cancel-read-when-in-set") "waitable cannot be used synchronously while added to a waitable set")
(component instance $i $Tester)
(assert_trap (invoke "sync-stream-cancel-write-when-in-set") "waitable cannot be used synchronously while added to a waitable set")
(component instance $i $Tester)
(assert_trap (invoke "sync-subtask-cancel-when-in-set") "waitable cannot be used synchronously while added to a waitable set")
