;; Runtime checks for variant/enum values originating in core wasm and
;; crossing a component-to-component boundary: discriminant range checks and
;; the flat-ABI join of differently-typed case payloads into one core slot.

;; Out-of-range discriminants trap when lifted, in both directions.
(component definition $BadDiscriminant
  (component $C
    (type $v32' (variant (case "x" u32)))
    (export $v32 "v32" (type $v32'))
    (type $v0' (variant (case "x")))
    (export $v0 "v0" (type $v0'))
    (type $e2' (enum "a" "b"))
    (export $e2 "e2" (type $e2'))
    (core module $M
      (func (export "take-variant") (param i32 i32))
      (func (export "give-variant") (result i32) (i32.const 1))
      (func (export "take-enum") (param i32))
      (func (export "give-enum") (result i32) (i32.const 2))
    )
    (core instance $m (instantiate $M))
    (func (export "take-variant") (param "v" $v32) (canon lift (core func $m "take-variant")))
    (func (export "give-variant") (result $v0) (canon lift (core func $m "give-variant")))
    (func (export "take-enum") (param "e" $e2) (canon lift (core func $m "take-enum")))
    (func (export "give-enum") (result $e2) (canon lift (core func $m "give-enum")))
  )
  (component $D
    (import "c" (instance $c
      (type $v32' (variant (case "x" u32)))
      (export "v32" (type $v32 (eq $v32')))
      (type $v0' (variant (case "x")))
      (export "v0" (type $v0 (eq $v0')))
      (type $e2' (enum "a" "b"))
      (export "e2" (type $e2 (eq $e2')))
      (export "take-variant" (func (param "v" $v32)))
      (export "give-variant" (func (result $v0)))
      (export "take-enum" (func (param "e" $e2)))
      (export "give-enum" (func (result $e2)))
    ))
    (core func $take-variant' (canon lower (func $c "take-variant")))
    (core func $give-variant' (canon lower (func $c "give-variant")))
    (core func $take-enum' (canon lower (func $c "take-enum")))
    (core func $give-enum' (canon lower (func $c "give-enum")))
    (core module $Main
      (import "" "take-variant" (func $take-variant (param i32 i32)))
      (import "" "give-variant" (func $give-variant (result i32)))
      (import "" "take-enum" (func $take-enum (param i32)))
      (import "" "give-enum" (func $give-enum (result i32)))
      (func (export "bad-variant-param") (call $take-variant (i32.const 1) (i32.const 0)))
      (func (export "bad-variant-result") (drop (call $give-variant)))
      (func (export "bad-enum-param") (call $take-enum (i32.const 2)))
      (func (export "bad-enum-result") (drop (call $give-enum)))
    )
    (core instance $main (instantiate $Main (with "" (instance
      (export "take-variant" (func $take-variant'))
      (export "give-variant" (func $give-variant'))
      (export "take-enum" (func $take-enum'))
      (export "give-enum" (func $give-enum'))
    ))))
    (func (export "bad-variant-param") (canon lift (core func $main "bad-variant-param")))
    (func (export "bad-variant-result") (canon lift (core func $main "bad-variant-result")))
    (func (export "bad-enum-param") (canon lift (core func $main "bad-enum-param")))
    (func (export "bad-enum-result") (canon lift (core func $main "bad-enum-result")))
  )
  (instance $c (instantiate $C))
  (instance $d (instantiate $D (with "c" (instance $c))))
  (func (export "bad-variant-param") (alias export $d "bad-variant-param"))
  (func (export "bad-variant-result") (alias export $d "bad-variant-result"))
  (func (export "bad-enum-param") (alias export $d "bad-enum-param"))
  (func (export "bad-enum-result") (alias export $d "bad-enum-result"))
)

(component instance $i $BadDiscriminant)
(assert_trap (invoke "bad-variant-param") "invalid variant discriminant")
(component instance $i $BadDiscriminant)
(assert_trap (invoke "bad-variant-result") "invalid variant discriminant")
(component instance $i $BadDiscriminant)
(assert_trap (invoke "bad-enum-param") "invalid variant discriminant")
(component instance $i $BadDiscriminant)
(assert_trap (invoke "bad-enum-result") "invalid variant discriminant")

;; Case payloads of different flat types share one joined core slot; only the
;; bits of the selected case's type survive the crossing.
(component
  (component $C
    (type $narrow' (variant (case "a" u8) (case "b" u32)))  ;; payload slot: i32
    (export $narrow "narrow-t" (type $narrow'))
    (type $wide' (variant (case "a" u16) (case "b" u64)))   ;; payload slot: i64
    (export $wide "wide-t" (type $wide'))
    (type $mix' (variant (case "f" f32) (case "l" u64)))    ;; payload slot: i64
    (export $mix "mix-t" (type $mix'))
    (core module $M
      (import "" "task.return" (func $task.return-mix (param i32 i64)))
      (func (export "narrow") (param i32 i32)
        (if (i32.eqz (local.get 0))
          (then (if (i32.ne (local.get 1) (i32.const 2)) (then unreachable)))
          (else (if (i32.ne (local.get 1) (i32.const 0xdeadbeef)) (then unreachable)))))
      (func (export "wide") (param i32 i64)
        (if (i32.eqz (local.get 0))
          (then (if (i64.ne (local.get 1) (i64.const 4)) (then unreachable)))
          (else (if (i64.ne (local.get 1) (i64.const 0x123456789abcdef0)) (then unreachable)))))
      (func (export "mix") (param i32 i64)
        (if (i32.eqz (local.get 0))
          (then (if (i64.ne (local.get 1) (i64.const 0x40490fdb)) (then unreachable)))
          (else (if (i64.ne (local.get 1) (i64.const 0xfedcba9876543210)) (then unreachable)))))
      (func (export "mix-ret")
        ;; f32 bits travel in the low half of the i64 join slot; high bits dropped
        (call $task.return-mix (i32.const 0) (i64.const 0xffffffff40490fdb)))
    )
    (canon task.return (result $mix) (core func $task.return-mix))
    (core instance $m (instantiate $M (with "" (instance
      (export "task.return" (func $task.return-mix))
    ))))
    (func (export "narrow") (param "v" $narrow) (canon lift (core func $m "narrow")))
    (func (export "wide") (param "v" $wide) (canon lift (core func $m "wide")))
    (func (export "mix") (param "v" $mix) (canon lift (core func $m "mix")))
    (func (export "mix-ret") async (result $mix) (canon lift (core func $m "mix-ret") async))
  )
  (component $D
    (import "c" (instance $c
      (type $narrow' (variant (case "a" u8) (case "b" u32)))
      (export "narrow-t" (type $narrow (eq $narrow')))
      (type $wide' (variant (case "a" u16) (case "b" u64)))
      (export "wide-t" (type $wide (eq $wide')))
      (type $mix' (variant (case "f" f32) (case "l" u64)))
      (export "mix-t" (type $mix (eq $mix')))
      (export "narrow" (func (param "v" $narrow)))
      (export "wide" (func (param "v" $wide)))
      (export "mix" (func (param "v" $mix)))
      (export "mix-ret" (func async (result $mix)))
    ))
    (core module $Memory (memory (export "mem") 1))
    (core instance $memory (instantiate $Memory))
    (core func $narrow' (canon lower (func $c "narrow")))
    (core func $wide' (canon lower (func $c "wide")))
    (core func $mix' (canon lower (func $c "mix")))
    (core func $mix-ret' (canon lower (func $c "mix-ret") async (memory (core memory $memory "mem"))))
    (core module $Main
      (import "" "mem" (memory 1))
      (import "" "narrow" (func $narrow (param i32 i32)))
      (import "" "wide" (func $wide (param i32 i64)))
      (import "" "mix" (func $mix (param i32 i64)))
      (import "" "mix-ret" (func $mix-ret (param i32) (result i32)))
      (func (export "join-narrow") (result i32)
        (call $narrow (i32.const 0) (i32.const 0xff02))  ;; u8 case: lifts as 2
        (call $narrow (i32.const 1) (i32.const 0xdeadbeef))
        (i32.const 42))
      (func (export "join-wide") (result i32)
        (call $wide (i32.const 0) (i64.const 0xff0004))      ;; u16 case: lifts as 4
        (call $wide (i32.const 0) (i64.const 0xff00000004))  ;; also wraps i64 to i32
        (call $wide (i32.const 1) (i64.const 0x123456789abcdef0))
        (i32.const 43))
      (func (export "join-f32") (result i32)
        (call $mix (i32.const 0) (i64.const 0xffffffff40490fdb))  ;; f32 bits in low half
        (call $mix (i32.const 1) (i64.const 0xfedcba9876543210))
        (i32.const 44))
      (func (export "ret-f32") (result i32)
        (if (i32.ne (call $mix-ret (i32.const 16)) (i32.const 2 (; RETURNED ;)))
          (then unreachable))
        (if (i32.ne (i32.load8_u (i32.const 16)) (i32.const 0)) (then unreachable))
        (if (i32.ne (i32.load offset=8 (i32.const 16)) (i32.const 0x40490fdb)) (then unreachable))
        (i32.const 45))
    )
    (core instance $main (instantiate $Main (with "" (instance
      (export "mem" (memory $memory "mem"))
      (export "narrow" (func $narrow'))
      (export "wide" (func $wide'))
      (export "mix" (func $mix'))
      (export "mix-ret" (func $mix-ret'))
    ))))
    (func (export "join-narrow") (result u32) (canon lift (core func $main "join-narrow")))
    (func (export "join-wide") (result u32) (canon lift (core func $main "join-wide")))
    (func (export "join-f32") (result u32) (canon lift (core func $main "join-f32")))
    (func (export "ret-f32") (result u32) (canon lift (core func $main "ret-f32")))
  )
  (instance $c (instantiate $C))
  (instance $d (instantiate $D (with "c" (instance $c))))
  (func (export "join-narrow") (alias export $d "join-narrow"))
  (func (export "join-wide") (alias export $d "join-wide"))
  (func (export "join-f32") (alias export $d "join-f32"))
  (func (export "ret-f32") (alias export $d "ret-f32"))
)

(assert_return (invoke "join-narrow") (u32.const 42))
(assert_return (invoke "join-wide") (u32.const 43))
(assert_return (invoke "join-f32") (u32.const 44))
(assert_return (invoke "ret-f32") (u32.const 45))
