;; Passing owns and borrows of a resource type R from a client component $D
;; back to the defining component $C: borrows leave the lender's own handle
;; usable after the call returns, but lifting an own traps while it is lent.
(component definition $BorrowTester
  (component $C
    (core module $Indirect
      (table (export "ftbl") 1 funcref)
      (type $FT (func (param i32)))
      (func (export "R-dtor") (param i32)
        (call_indirect (type $FT) (local.get 0) (i32.const 0))
      )
    )
    (core instance $indirect (instantiate $Indirect))
    (type $R' (resource (rep i32) (dtor (core func $indirect "R-dtor"))))
    (export $R "R" (type $R'))
    (canon resource.new $R' (core func $resource.new))
    (canon resource.drop $R' (core func $resource.drop))

    (core module $CM
      (import "" "ftbl" (table 1 funcref))
      (import "" "resource.new" (func $resource.new (param i32) (result i32)))
      (import "" "resource.drop" (func $resource.drop (param i32)))
      (global $num-made (mut i32) (i32.const 0))
      (global $num-live (mut i32) (i32.const 0))

      (func (export "make") (result i32)
        (global.set $num-made (i32.add (global.get $num-made) (i32.const 1)))
        (global.set $num-live (i32.add (global.get $num-live) (i32.const 1)))
        (call $resource.new (i32.add (i32.const 0x40) (global.get $num-made)))
      )

      ;; borrow params arrive as the rep since $C implements R
      (func (export "get-rep") (param $rep i32) (result i32)
        (local.get $rep)
      )
      (func (export "get-rep-pair") (param $rep1 i32) (param $rep2 i32) (result i32)
        (i32.add (local.get $rep1) (local.get $rep2))
      )

      (func (export "borrow-and-take") (param $rep i32) (param $own i32) (result i32)
        (call $resource.drop (local.get $own))
        (local.get $rep)
      )

      (func (export "num-live") (result i32)
        (global.get $num-live)
      )
      (func $dtor (param $rep i32)
        (if (i32.or (i32.le_u (local.get $rep) (i32.const 0x40))
                    (i32.gt_u (local.get $rep) (i32.add (i32.const 0x40) (global.get $num-made))))
          (then unreachable))
        (if (i32.eqz (global.get $num-live))
          (then unreachable))
        (global.set $num-live (i32.sub (global.get $num-live) (i32.const 1)))
      )
      (elem (i32.const 0) $dtor)
    )
    (core instance $cm (instantiate $CM (with "" (instance
      (export "ftbl" (table $indirect "ftbl"))
      (export "resource.new" (func $resource.new))
      (export "resource.drop" (func $resource.drop))
    ))))
    (func (export "make") (result (own $R)) (canon lift (core func $cm "make")))
    (func (export "get-rep") (param "r" (borrow $R)) (result u32) (canon lift (core func $cm "get-rep")))
    (func (export "get-rep-pair") (param "a" (borrow $R)) (param "b" (borrow $R)) (result u32) (canon lift (core func $cm "get-rep-pair")))
    (func (export "borrow-and-take") (param "b" (borrow $R)) (param "o" (own $R)) (result u32) (canon lift (core func $cm "borrow-and-take")))
    (func (export "num-live") (result u32) (canon lift (core func $cm "num-live")))
  )

  (component $D
    (import "c" (instance $c
      (export "R" (type $R (sub resource)))
      (export "make" (func (result (own $R))))
      (export "get-rep" (func (param "r" (borrow $R)) (result u32)))
      (export "get-rep-pair" (func (param "a" (borrow $R)) (param "b" (borrow $R)) (result u32)))
      (export "borrow-and-take" (func (param "b" (borrow $R)) (param "o" (own $R)) (result u32)))
      (export "num-live" (func (result u32)))
    ))
    (core module $DM
      (import "" "resource.drop" (func $resource.drop (param i32)))
      (import "" "make" (func $make (result i32)))
      (import "" "get-rep" (func $get-rep (param i32) (result i32)))
      (import "" "get-rep-pair" (func $get-rep-pair (param i32 i32) (result i32)))
      (import "" "borrow-and-take" (func $borrow-and-take (param i32 i32) (result i32)))
      (import "" "num-live" (func $num-live (result i32)))

      (func (export "run") (result i32)
        (local $h1 i32) (local $h2 i32) (local $h3 i32)
        (local.set $h1 (call $make))
        (if (i32.ne (i32.const 1) (local.get $h1))
          (then unreachable))

        (if (i32.ne (i32.const 0x41) (call $get-rep (local.get $h1)))
          (then unreachable))
        (if (i32.ne (i32.const 0x41) (call $get-rep (local.get $h1)))
          (then unreachable))

        (if (i32.ne (i32.const 0x82) (call $get-rep-pair (local.get $h1) (local.get $h1)))
          (then unreachable))

        (local.set $h2 (call $make))
        (if (i32.ne (i32.const 2) (local.get $h2))
          (then unreachable))
        (if (i32.ne (i32.const 2) (call $num-live))
          (then unreachable))
        (if (i32.ne (i32.const 0x41) (call $borrow-and-take (local.get $h1) (local.get $h2)))
          (then unreachable))
        (if (i32.ne (i32.const 1) (call $num-live))
          (then unreachable))

        (if (i32.ne (i32.const 0x41) (call $get-rep (local.get $h1)))
          (then unreachable))
        (call $resource.drop (local.get $h1))
        (if (i32.ne (i32.const 0) (call $num-live))
          (then unreachable))

        (local.set $h3 (call $make))
        (if (i32.ne (i32.const 1) (local.get $h3))
          (then unreachable))
        (if (i32.ne (i32.const 0x43) (call $get-rep (local.get $h3)))
          (then unreachable))
        (call $resource.drop (local.get $h3))

        (i32.const 42)
      )

      (func (export "lend-trap")
        (local $h i32)
        (local.set $h (call $make))
        (drop (call $borrow-and-take (local.get $h) (local.get $h)))
      )
    )
    (alias export $c "R" (type $R))
    (canon resource.drop $R (core func $resource.drop))
    (canon lower (func $c "make") (core func $make'))
    (canon lower (func $c "get-rep") (core func $get-rep'))
    (canon lower (func $c "get-rep-pair") (core func $get-rep-pair'))
    (canon lower (func $c "borrow-and-take") (core func $borrow-and-take'))
    (canon lower (func $c "num-live") (core func $num-live'))
    (core instance $dm (instantiate $DM (with "" (instance
      (export "resource.drop" (func $resource.drop))
      (export "make" (func $make'))
      (export "get-rep" (func $get-rep'))
      (export "get-rep-pair" (func $get-rep-pair'))
      (export "borrow-and-take" (func $borrow-and-take'))
      (export "num-live" (func $num-live'))
    ))))
    (func (export "run") (result u32) (canon lift (core func $dm "run")))
    (func (export "lend-trap") (canon lift (core func $dm "lend-trap")))
  )

  (instance $c (instantiate $C))
  (instance $d (instantiate $D (with "c" (instance $c))))
  (func (export "run") (alias export $d "run"))
  (func (export "lend-trap") (alias export $d "lend-trap"))
)

(component instance $i $BorrowTester)
(assert_return (invoke "run") (u32.const 42))

(component instance $i $BorrowTester)
(assert_trap (invoke "lend-trap") "cannot remove owned resource while borrowed")
