name: CI

on:
  push:
  pull_request:

jobs:
  canonical_abi:
    name: Run Canonical ABI Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: python design/mvp/canonical-abi/run_tests.py
